- gunicorn/workers/gthread.py
this change makes sure that a worker don't handle more requests than it can achieved.  The new workflow is quite more simple:
1. listeners are put in the poller. On read we try to accept on them.
2. When a connection is accepted it is put in the execution queue
3. When a request is done and the socket can be kept alived, we put it in the poller, on read event we will try to handle the new request. 
4. If it is not put out of the poller before the keepalive timeout the socket will be closed.
5. if all threads are busy we are waiting until one request complet. If it doesn't complete before the timeout we kill the worker.
fix #908
> stop to accept more requests when maximum accepted is achieved

- gunicorn/glogging.py
This way it will be easier to change log level of a custom
Logger class:
class MyLogger(gunicorn.glogging.Logger):
loglevel = logging.WARNING
> Make Logger.loglevel a class attribute.

- gunicorn/util.py
- gunicorn/workers/base.py
This implements the feature requested in issue #964.
When there is `SyntaxError` raised while importing the app, provides a fallback app to display those errors instead of completely exit gunicorn.
> reloader should survive SyntaxError

- gunicorn/sock.py
I'm using gunicorn in an embedded virtual networking application, and it's not uncommon for the bind address to take a few moments to actually be added to the interface.  Given that other socket binding failures in this method lead to a retry loop, it seems reasonable that this one would as well?
> Retry socket binding up to five times upon EADDRNOTAVAIL.

- docs/source/design.rst
Currently, we introduce this document as a description
of "an" architecture of Gunicorn, which makes it sound
like this document describes one of many Gunicorn
architectures, which doesn't make a lot of sense.
Clarify the grammar by introducing the document as a
description of "the" Gunicorn architecture.
> design.rst: grammar

- gunicorn/glogging.py
- gunicorn/instrument/statsd.py
- tests/test_010-statsd.py
`statsd` logging appears to be (silently) broken in Python 3, because it passes it passes `unicode` (i.e. not `bytes`) to the `sock.send` method.
This PR:
+ Ensures `bytes` are used
+ Adds tests that actually go through an actual (UNIX) socket to ensure those errors can be caught in uni testing in the future.
+ Logs `statsd` errors as warnings (the exceptions being silently swallowed made them difficult to troubleshoot)
> Fix statsd Logging in Python 3

- gunicorn/workers/gthread.py
Use `nr_conns` for counting the connections and `self.nr` for counting the requests.
Closes #1030
> Fix self.nr usage in ThreadedWorker so that auto restart works as expected

- docs/source/deploy.rst
This PR updates the Gunicorn deploy documentation on why `REMOTE_ADDR` may not always be the IP address of the user.
Close: #1035
Related: #633 
Signed-off-by: Hans Kristian Flaatten <hans.kristian.flaatten@turistforeningen.no>
> Document why REMOTE_ADD may not be the user's IP address

- gunicorn/arbiter.py
The fix for issue #863 was incomplete as both OSError or ValueError could be
raised by os.fstat(). Thus we need to catch both types of exceptions
Additionally fixed some PEP8 formatting issues.
> Catch OSError as well as ValueError on race condition

- gunicorn/workers/ggevent.py
In python3 gevent (1.1a1) we have different socket interface, which does not have _sock method.
It's compatible with python standard library socket and have just fileno param.
Here's the socket for python3 code in gevent repo -  https://github.com/gevent/gevent/blob/dedb08cf210ebae1ac059150a05542a10d285926/gevent/_socket3.py#L35
> add support for gevent on python3

- gunicorn/glogging.py
Logging Basic auth username to access log:
```
curl -u brk0v: -i -k https://api.example.com/v1/api-call
```
Logs:
```
127.0.0.1 - brk0v [07/Jul/2015:23:37:34 +0300] "GET /v1/api-call HTTP/1.1" 200 307 "-" "curl/7.21.3 libcurl/7.21.3"
```
> Getting username from basic auth header for access logs

- gunicorn/pidfile.py
Added a try block to convert the contents of the `pidfile.py` if it can be converted to integer or not. If not, then `wpid` is assigned 0 and the `validate` function returns as usual. If the pidfile has a valid int, the function continues to kill the process as before.
> Updated gunicorn/pidfile.py

- docs/source/run.rst
- docs/source/settings.rst
- gunicorn/app/base.py
- gunicorn/config.py
- tests/test_config.py
Fixes #836 as described in @benoitc's [comment](https://github.com/benoitc/gunicorn/issues/836#issuecomment-50957348).
> Prefix config file with its type

- docs/source/settings.rst
- gunicorn/config.py
Show that setting multiple paths requires using a comma-separated list.
> Clarify pythonpath setting description

- gunicorn/sock.py
- gunicorn/workers/geventlet.py
When the worker was exiting, eventlet is closing the listening socket in th
worker. Since the socket instances are shared, this was also removing the unix
socket on close. This change make sure that the socket can only be closed by
its parent (where the socket have been bound).
While I'm here, also make sure we don't use any blocking function in eventlet
while switching).
fix #965
> don't close the unix socket when the worker exit

- gunicorn/arbiter.py
Otherwise when debug logging is on, the message prints every second even with no system activity, drowning out more useful log messages:
```
[2015-07-12 17:39:25 +0000] [19970] [DEBUG] 3 workers
[2015-07-12 17:39:26 +0000] [19970] [DEBUG] 3 workers
[2015-07-12 17:39:27 +0000] [19970] [DEBUG] 3 workers
[2015-07-12 17:39:28 +0000] [19970] [DEBUG] 3 workers
[2015-07-12 17:39:29 +0000] [19970] [DEBUG] 3 workers
[2015-07-12 17:39:30 +0000] [19970] [DEBUG] 3 workers
[2015-07-12 17:39:31 +0000] [19970] [DEBUG] 3 workers
[2015-07-12 17:39:32 +0000] [19970] [DEBUG] 3 workers
[2015-07-12 17:39:33 +0000] [19970] [DEBUG] 3 workers
[2015-07-12 17:39:34 +0000] [19970] [DEBUG] 3 workers
[2015-07-12 17:39:35 +0000] [19970] [DEBUG] 3 workers
[2015-07-12 17:39:36 +0000] [19970] [DEBUG] 3 workers …
```
> Only log '[num] workers' message when it changes.

- gunicorn/workers/_gaiohttp.py
Initialize and pass `SSLContext` to `asyncio.loop.create_server` to enable ssl support.
Once again - see #1092
> SSL support for gaiohttp worker

- gunicorn/http/wsgi.py
- gunicorn/util.py
- tests/test_http.py
Hi,
gunicorn uses utf8 encoding for http response headers. I don't know
much about http standards, but this is probably not correct:
http://stackoverflow.com/questions/4400678/http-header-should-use-what-character-encoding
best regards,
Jochen
> ISO-8859-1 encoded http headers

- docs/site/index.html
- docs/source/deploy.rst
- docs/source/install.rst
- docs/source/instrumentation.rst
- docs/source/signals.rst
Updated Debian/Ubuntu installation docs as installation documents for Debian and Ubuntu got obsolete.
For Ubuntu, the guide for lucid may now be deleted as [it reached EOL in Apr 2015](http://fridge.ubuntu.com/2015/03/18/ubuntu-10-04-lucid-lynx-reaches-end-of-life-on-april-30-2015/).
> Update Debian/Ubuntu installation instructions.

- gunicorn/arbiter.py
This change makes sure we don't recreate the Logger class here so we
don't reinitialise the log handlers.
fix #627
> makes sure that file handles are correctly reopened on HUP

- gunicorn/workers/gtornado.py
Tornado add many timeouts internally which can be ignored while graceful stopping.
> remove checking timeouts while graceful stopping tornado worker

- gunicorn/app/pasterapp.py
The values of both the 'workers' and 'umask' settings have global defaults. In the case of 'workers', this global default can be overridden by the WEB_CONCURRENCY environment variable, which is currently ignored when running an application with `gunicorn --paste`.
Removing this duplication of defaults allows `gunicorn --paste` to respect settings from:
- the environment (WEB_CONCURRENCY)
- the paste configuration file
- CLI flags
> Respect defaults when running a paster application

- docs/source/settings.rst
- gunicorn/config.py
Username parameter has been implemented in https://github.com/benoitc/gunicorn/pull/1069 .
> Fix config description of accesslog user-name params

- THANKS
- gunicorn/workers/ggevent.py
As discussed in #1126. This fixes the problem interactively. However, I have no idea how to add a unit test; there doesn't seem to be anything similar in place already. Suggestions welcome!
> Make the gevent workers handle the quit signal by deferring to a new greenlet

- docs/source/faq.rst
Fix the _worker_class_ link at http://docs.gunicorn.org/en/19.3/faq.html#worker-processes
> Fix worker class link in FAQ

- docs/source/faq.rst
Fixes the link to the `proc_name` setting on the FAQ [here](http://docs.gunicorn.org/en/19.3/faq.html#how-can-i-name-processes), since it no longer exists on the configure page.
> Docs: Fix the link to the proc_name setting on the FAQ page

- gunicorn/workers/gtornado.py
Fixes #1135
All tests were passed, but I did not add tests for this update, sorry.
> fix-ssl-options-for-tornado

- gunicorn/http/wsgi.py
- gunicorn/util.py
A safe and reliable check for whether a file descriptor supports mmap
is to directly check if it is seekable. However, some seekable file
descriptors may also report a zero size when calling fstat. If there
is no content length specified for the response and it cannot be
determined from the file descriptor then it is not possible to know
what chunk size to send to the client. In this case, is it necessary
to fall back to unwinding the body by iteration.
The above conditions together reveal a straightforward and reliable
way to check for sendfile support. This patch modifies the Response
class to assert these conditions using a try/catch block as part of
a new, simplified sendfile method. This method returns False if it
is not possible to serve the response using sendfile. Otherwise, it …
> Simplify sendfile logic

- gunicorn/workers/gtornado.py
gtornado worker always crashes because of this random outdent.
> Fix random outdent which makes gtornado worker unusable

- gunicorn/config.py
- gunicorn/sock.py
**Fast Open** is a optimization to the process of stablishing a TCP connection that
allows the elimination of one round time trip (RTT) from certain kinds of TCP
conversations. Fast Open could result in speed improvements of between 4% and
41% in the page load times on popular web sites.
Available on linux >= 3.7.1.
More info:
- https://lwn.net/Articles/508865/
- http://research.google.com/pubs/pub37517.html
> support TCP Fast Open option

- gunicorn/arbiter.py
In Arbiter#run() the call to self.manage_workers() can also raise HaltServer, but it's outside the try block where it is handled.
For example (from [RHBZ#1200041](https://bugzilla.redhat.com/show_bug.cgi?id=1200041)):
```
File "/usr/bin/gunicorn", line 9, in <module>
load_entry_point('gunicorn==19.1.1', 'console_scripts', 'gunicorn')()
File "/usr/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
File "/usr/lib/python2.7/site-packages/gunicorn/app/base.py", line 185, in run
super(Application, self).run()
File "/usr/lib/python2.7/site-packages/gunicorn/app/base.py", line 71, in run
Arbiter(self).run()
File "/usr/lib/python2.7/site-packages/gunicorn/arbiter.py", line 169, in run …
```
> handle HaltServer in manage_workers

- gunicorn/glogging.py
- gunicorn/util.py
This change will check if the file is writable before trying to own it. There is no reason to do a `os.fchown` if we can already write on it.
fix #1157
> check auth before trying to own a file

- gunicorn/config.py
sendfile option don't set any default for now which makes the validation fail
(and then tests) since no boolean is given. For now just return when the value
is not set.
> fix sendfile option validation

- gunicorn/glogging.py
- gunicorn/util.py
Some systems edisable like SELINUX disable some flags so ignore the possible
error while chowning a log file. The error will be raised later anyway.
fix #1171
> don't check if a file is writable using os.stat

- gunicorn/http/wsgi.py
- gunicorn/util.py
`util.is_fileobject` usage was removed due to the use of the `tell` method check.
This change remove this check wich allows us to completely test if
fileno() is usable. Also it handle most of the exceptions around created by
breaking changes across Python versions. Hopefully we are good now.
fix #1174
> reuse util.is_fileobject

- gunicorn/http/wsgi.py
when fixing the fileno for BytesIO, actually setting fileno has been forogtten
tests said: 131 passed, 46 skipped
> Fix NameError fileno in gunicorn.http.wsgi

- gunicorn/http/wsgi.py
Ensure that Gunicorn won't try to use chunked transfer-encoding for responses
to a HEAD request, so that `Response.close` will not write a terminating
chunk. Responses to a HEAD request MUST NOT have a message-body.
The application is still responsible for ensuring no message body is actually
generated in response to a HEAD request.
Refs #990
> Ensure response to HEAD request won't have message body

- gunicorn/workers/async.py
- gunicorn/workers/gthread.py
- gunicorn/workers/sync.py
This pull request merges working code to fix the `BrokenPipeError` exceptions being thrown on Python 3 + eventlet.  It has been tested on a large application serving millions of requests hourly.
> use EnvironmentError instead of socket.error (closes #939)

- gunicorn/glogging.py
- gunicorn/instrument/statsd.py
- gunicorn/workers/_gaiohttp.py
Access logs were wrongly formatted when using gaiohttp worker
It also fixes the statsd instrumentation with this type of worker.
> fix access logging in gaiohttp worker

- gunicorn/arbiter.py
Currently, on some errors, tracebacks are manually included in the log message. This patch instead uses the stdlibs logging traceback printing.  This allow better log customisation and control.
Additionally, because the call to logging.exception included the traceback in its log message, the traceback was printed twice the logs, as logging.exception always prints the traceback.
I've left the exceptions logged at debug/info as they are, but it seems to me they'd be better off as error level, since we sys.exit() after both anyway,
> Clean up traceback printing in arbitar

- gunicorn/config.py
This pull request gives gunicorn the ability to have the `ForwardedAllowIPS` setting (e.g. `--forwarded-allow-ips`) default configured via the environment variable `FORWARDED_ALLOW_IPS`. Similar behavior is currently in gunicorn for `$WEB_CONCURRENCY` and the `Workers` setting.
This will allow Heroku users to have a better default Gunicorn configuration out of the box, and will alleviate the need to use ProxyFix middleware in WSGI applications, without effecting their codebase.
:sparkles: :cake: :sparkles:
> $FORWARDED_ALLOW_IPS

- examples/example_config.py
This fixes the URL in the example_config.py
> Fix URL and default worker type in example_config

- docs/source/settings.rst
- gunicorn/config.py
- tests/test_config.py
Currently if you configure statsd_host, a configured logger_class will never be used.
I think this makes a user configured logger class always take priority.
(This is PoC change, I will come back and add tests/docs if it's worth pursuing)
> Allow configuring logger_class with statsd_host

- gunicorn/app/djangoapp.py
- gunicorn/management/commands/run_gunicorn.py
When updating our company's gunicorn I noticed the doc link for django was out of date.  Looks like django removed all docs before 1.7.  Another option, which would avoid updating these docs every few years would be to point those urls to `dev`, eg: https://docs.djangoproject.com/en/dev/howto/deployment/wsgi/gunicorn/
Thanks for the project!
> update django doc url to 1.8 lts

- gunicorn/sock.py
By having a `getattr` implementation that proxies to the `sock`
attribute, there is a risk of infinite recursion when the socket
attribute is absent. After closing the socket and destroying it,
the recursion can be prevented by setting the attribute to `None`.
> fix infinite recursion when destroying sockets

- gunicorn/arbiter.py
- tests/test_arbiter.py
Close all the listeners when the arbiter shuts down. By doing so,
workers can close the socket at the beginning of a graceful shut
down thereby informing the operating system that the socket can
be cleaned up. With this change, graceful exits with such workers
will refuse new connections while draining, allowing load balancers
to respond more quickly and avoiding leaving connections dangling
in the listen backlog, unaccepted.
Ref #922
> [arbiter] close sockets on shutdown

- NOTICE
I want to use gunicorn in production environment. However, I found a license problem which prevent me from using gunicorn in production of my company.
It looks like that selectors.py is the copy of https://github.com/python/cpython/blob/master/Lib/selectors.py.
I think we should add PSF License Agreement to this file according to the license.
https://docs.python.org/2/license.html
https://docs.python.org/3/license.html
Cloud you add license agreement?
Thanks.
> Add PSF License Agreement to selectors.py

- gunicorn/_compat.py
- gunicorn/workers/async.py
- gunicorn/workers/base.py
- gunicorn/workers/gthread.py
- gunicorn/workers/sync.py
As part of pulling in 2e231d20d51677949067247d8133734943ca0a72 and a3f6df5b7e37eba4d45c841b0c0c5b3fc983258b, EPIPEs result in the `EnvironmentError` exception handler in `handle()` being run. In many environments, EPIPEs can be extremely common. The exception handler stores the traceback into a local variable, creating a circular reference, and prevents the system socket (holding a fd open along with other socket resources) from being closed until the next Python full garbage collection cycle. The behavior of `sys.exec_info()` is documented at https://docs.python.org/2/library/sys.html#sys.exc_info with a large red warning statement. This new exception path for EPIPEs can create significant additional resource usage for gunicorn installations.
Removing the assignment into `exc_info` …
> Fix delayed socket close caused by circular ref from assigning traceback to local var

- gunicorn/workers/base.py
Try to not crash when reporting an error. This changes makes sure we can log the uri and also handle SSL errors.
fix #1177
> prevent crash when reporting an error

- gunicorn/workers/geventlet.py
Just like in the gevent worker, a blocking call should only be executed
from within a coroutine. The AssertionError around the main loop of the
eventlet worker can be removed, since it was there to catch
the exception raised by the sleep.
> [eventlet] handle QUIT in a new coroutine

- gunicorn/workers/base.py
Without this patch, on current Gunicorn version I get the following traceback if I have a syntax error in my program:
```
...
File "/home/mars/myproject/views/item.py", line 494
return render(request, 'add_item.html',
^
SyntaxError: invalid syntax
During handling of the above exception, another exception occurred:
File "/usr/lib/python3.5/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
worker.init_process()
File "/usr/lib/python3.5/site-packages/aiohttp-0.21.2-py3.5-linux-x86_64.egg/aiohttp/worker.py", line 30, in init_process
super().init_process()
File "/usr/lib/python3.5/site-packages/gunicorn/workers/base.py", line 122, in init_process
self.load_wsgi()
File "/usr/lib/python3.5/site-packages/gunicorn/workers/base.py", line 140, in …
```
> Fixed traceback formatting for syntax errors

- gunicorn/workers/gthread.py
The run loop has to change slightly to support graceful shutdown.
There is no way to interrupt a call to `futures.wait` so instead
the pattern, used by the async workers, is to sleep for only one
second at the most. The poll is extended to a one second timeout
to match.
Since threads are preemptively scheduled, it's possible that the
listener is closed when the request is actually handled. For this
reason it is necessary to slightly refactor the TConn class to store
the listening socket name. The name is checked once at the start of
the worker run loop.
Ref #922
> [thread] close sockets at graceful shutdown

- gunicorn/workers/geventlet.py
Implement early closing of sockets for eventlet graceful shutdown, just like we have in gevent.
Ineffectual without #1221, but with that applied both workers immediately refuse new connections once graceful shutdown starts.
> [eventlet] close sockets at graceful shutdown

- gunicorn/workers/ggevent.py
Since the changes from #1126, errors are not raised into the main
loop during a non-graceful shutdown. Therefore, these exception
clauses shouldn't be needed anymore.
> [gevent] remove obsolete exception clauses in run

- THANKS
- tests/t.py
- tests/test_http.py
In this PR I added unit tests for Unreader and its subclasses. Also I fixed `recv` method of `FakeSocket` because it doesn't use `length` argument.
> Unreader unit tests

- gunicorn/workers/base.py
After 81f65c2 it became impossible to get access to application in post_worker_init, because application not loaded yet. This patch return previous behaviour.
> do post_worker_init after load_wsgi

- examples/example_config.py
The example given is the current default log format.
I found myself looking through the code to figure out how to set this, so hopefully this will save other peoples time.
> Add access_log_format to config example

- gunicorn/workers/base.py
- gunicorn/workers/sync.py
in python 3.5 the select is blocking when waiting for it which prevent quick
exit on SIGTERM.
The problem is described:
https://www.python.org/dev/peps/pep-0475/#backward-compatibility
This change fix it by listening for signal event on the worker pipe. Once an
event is triggered it will forcefully wake up the select and return.
fix #1256
> unblock the wait loop under python 3.5

- THANKS
- docs/source/settings.rst
- gunicorn/arbiter.py
This tackles #1253.
I have also added a commit proposing a documentation change: when I read the current doc for the `worker_exit()` hook, I was not sure if it's actually executed *in* the worker process (right before it terminates), or in the master process (right after it has terminated).
Please have a look, thanks!
> Do not swallow exception raised during worker exit 

- docs/source/design.rst
Just a formatting fix. In preview, `this feature` was coming in next line.
> Fix note for design.rst

- gunicorn/arbiter.py
- gunicorn/config.py
- gunicorn/lockfile.py
- gunicorn/sock.py
- gunicorn/util.py
- tests/test_arbiter.py
- tests/test_lockfile.py
- tests/test_sock.py
This change add proper file locking to gunicorn. By default "gunicorn.lock" is created in the temporary directory when a unix socket is bound.  In case someone want to fix the lock file path or use multiple gunicorn instance the "--lock-file" setting can be used to set the path of this file.
fix #1259
> fix unix socket locking

- gunicorn/workers/base.py
Killing ourself when using the `--reload` option trigger an infinite loop under some monitoring services like the one in pycharm and don't reload the file.
Instead set self.alive as False which will trigger later the worker exit. Note that if we want to force the exit we could also use sys.exit(0) .
fix #1129
> don't kill ourself on reload

- gunicorn/arbiter.py
- gunicorn/lockfile.py
- gunicorn/sock.py
- tests/test_arbiter.py
- tests/test_lockfile.py
- tests/test_sock.py
- rename LockFile.lock  to acquire
- rename LockFile.unlock to release
- move the lockfile management in sepate functions inside the arbiter
- remove the "closed" argument from the socket.close method and add a new "destroy" function that will be called whent  the socket can be unlinked (cal release)
- fix tests
related to #1263 discussion
> lockfile improvements

- gunicorn/arbiter.py
Calling pre_exec before copying the environment will allow to make environment modifications before spawning new master.
> Allow to modify environment in pre_exec callback

- gunicorn/workers/gthread.py
when it happend there are good chance the socket has been removed because it timeouted on the other end. So ignore it.
fix #1258
> gthread: handle removed socket in the select loop

- docs/source/settings.rst
> timeout setting, rewrote what it means for a worker be silent

- docs/source/deploy.rst
As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.
> Convert readthedocs link for their .org -> .io migration for hosted projects

- gunicorn/config.py
- gunicorn/util.py
- gunicorn/workers/base.py
Allows the possibility to initialise the group access list when needed to separate privileges
fix #1287
> initialize  the group access list for a worker when initgroups is set

- docs/source/settings.rst
- gunicorn/config.py
- gunicorn/glogging.py
Add environment variables to gunicorn access log format using `{Variable}e`.
Updated the docs to include the new identifier.
> Add environment variables to gunicorn access log format

- gunicorn/app/wsgiapp.py
- gunicorn/config.py
While bootstraping gunicorn with `paster` (PasteScript) or `pserve` (Pyramid) is now discouraged, no options are provided for PasteDeploy users to set global configuration variables from the commandline.
This patch adds the new commandline option `--paste-global-conf KEY=VALUE` so that the users can pass arbitrary global_conf values to the PasteDeploy entrypoint.
> Add --paste-global-conf option

- gunicorn/util.py
Useful when you have a NameError in the code that creates your app.
> feat(import_app): print original exception on AppImportError

- docs/source/deploy.rst
systemd example starts the wrong service name. Could cause confusion for beginners.
> Fixed mistake in systemd section

- gunicorn/sock.py
I've made the tweaks suggested by @berkerpeksag here: https://github.com/benoitc/gunicorn/pull/1131 
cc @benoitc @smilliken @tilgovi @pypeng
> Updated "Enable SO_REUSEPORT socket option"

- gunicorn/sock.py
- tests/test_sock.py
`socket.fromfd` does not close the original file descriptor, so we have to explicitly close it to avoid a leak.
See also:
http://bugs.python.org/issue10099
> Fix leak of duplicate file descriptor for bound sockets.

- THANKS
- docs/source/settings.rst
- gunicorn/config.py
- gunicorn/reloader.py
- gunicorn/workers/base.py
Currently, `--reload` uses FS polling to find out when files have changed. For some time, the Linux kernel has had a feature called inotify that allows applications to monitor for FS events without polling.
This commit adds a new `use-inotify` configuration option that will cause gunicorn to use the new `InotifyReloader` instead of the default `Reloader` when `reload` is enabled.
Using inotify can result in lower CPU consumption by gunicorn especially when working with virtualized filesystems or environments with a large number of watched files / directories.
> Add InotifyReloader and updated '--reload {poll,inotify}' configuration option

- docs/source/settings.rst
- gunicorn/config.py
- gunicorn/workers/base.py
When '--reload=RELOADER_TYPE' was implemented, `validate_reload()` was
added but in one of the last refactorings, it lost the return statement
at the end of the function. As a result, the '--reload' config value was
totally broken.
This resolves the issue by adding the missing return.
My first commit failed because the default value of the setting (`None`) was not the same as the output of its validator when `None` was passed in. At this point, I realized that trying to keep ``--reload`` (with no argument) is virtually impossible because of the ambiguity when we allow `--reload` by itself and `--reload RELOADER_TYPE`. For instance, running `gunicorn --reload myapp:app` now results in an error because `myapp:app` is now seen as the argument to `--reload` instead of the app module name.
I …
> Fix validate_reload by returning the validated value

- gunicorn/http/message.py
- tests/requests/invalid/018.http
- tests/requests/invalid/018.py
Numbers must be separated by dot. This makes life
a little bit harder for attackers who would like to inject specially crafted packets after GET / (e.g. in nginx there are sometimes regular expressions like (?P<action>[^.]).html
> Reject requests like "GET / HTTP/1a1"

- docs/source/deploy.rst
Without this /run/gunicorn isn't created.
> Add RuntimeDirectory to systemd service

- gunicorn/workers/base.py
This resolves the issue introduced in https://github.com/benoitc/gunicorn/commit/64b26ef76648ad2a70f64379f0f5433117450529
> Fix #1397 by calling load_wsgi after starting the reloader

- gunicorn/workers/async.py
- gunicorn/workers/geventlet.py
fixes https://github.com/benoitc/gunicorn/issues/1210
> add support for eventlets _AlreadyHandled object

- gunicorn/config.py
The documentation suggests that the value is optional, but without
this change it is not.
> allow --reload without any value

- gunicorn/arbiter.py
- gunicorn/sock.py
- gunicorn/systemd.py
- tests/test_arbiter.py
- tests/test_sock.py
- tests/test_systemd.py
Track the use of systemd socket activation and gunicorn socket inheritance
in the arbiter. Unify the logic of creating gunicorn sockets from each of
these sources to always use the socket name to determine the type rather
than checking the configured addresses. The configured addresses are only
used when there is no inheritance from systemd or a parent arbiter.
Fix #1298
> Refactor socket activation and fd inheritance

- docs/source/community.rst
- docs/source/custom.rst
- docs/source/deploy.rst
- docs/source/design.rst
- docs/source/faq.rst
- docs/source/signals.rst
- gunicorn/config.py
Minor documentation fixes and use 79  as max line length in docs.
> Minor fixes in docs and doc's code-style

- docs/source/deploy.rst
Got rid of duplicate nginx.conf included earlier in the documentation.
> only have essential nginx.conf settings

- THANKS
- gunicorn/app/base.py
- gunicorn/config.py
- tests/test_config.py
add environment variables that starts with `GUNICORN_` like `GUNICORN_WORKERS` as settings.
skip variables that does not start with `GUNICORN_`, and also skip variable that not in `settings` like `GUNICORN_FOO`
> add ability to pass in all config values as environment variables.

- docs/source/news.rst
- docs/source/signals.rst
> Document pidfile naming format change in 19.6.0

- gunicorn/arbiter.py
- gunicorn/config.py
- gunicorn/workers/base.py
- tests/test_arbiter.py
This adds a `child_exit()` callback to the Gunicorn configuration that works similar to `worker_exit()` but is called in the *master* process instead of the *child process*.
I also added some basic unit tests for the both.
A change to how `Worker.pid` is implemented was necessary in order for it to be meaningful in the master process (it would always be the PID of the master process, no information given about the worker process).
Our need for this is prometheus/client_python#115
> Add child_exit() callback to configuration

- docs/source/signals.rst
I've updated the signal handling documentation to make its use of reST markup and common terms consistent with the rest of the Gunicorn documentation.
> Tweak signal handling documentation

- docs/source/design.rst
- docs/source/settings.rst
- gunicorn/config.py
In response to #1045 minor tweaks to the documentation to emphasize that
the `--threads` setting is only applied to the `gthread` worker.
> Doc tweaks around threads setting

- setup.cfg
- tox.ini
This makes the experience of running pytest consistent whether pytest was called from the command line using `py.test` or via `tox`.
> move pytest cli args to setup.cfg

- .gitignore
- .travis.yml
- setup.cfg
This publishes coverage reports of each travis build to www.couverture.io
Steps needed to be taken by @benoitc in order for this to work:
* go to www.couverture.io and click "enable" on the gunicorn repository.
I will iterate on this PR as necessary once the step mentioned above is completed. Thanks! :)
> submit coverage report to couverture.io

- gunicorn/config.py
- gunicorn/reloader.py
- gunicorn/workers/base.py
- tests/test_config.py
Currently, gunicorn automatically uses the preferred reloader (inotify
if present with fallback to polling). However, it would be useful in
some scenarios if users could force polling.
The solution for this is to add a new configuration option called
'reload_engine' which takes one of three options: ['auto', 'poll',
'inotify'].
Fixes #1459
> Add support for --reload-engine

- gunicorn/config.py
- gunicorn/http/wsgi.py
- gunicorn/instrument/statsd.py
- gunicorn/util.py
https://pypi.python.org/pypi/vulture
In particular the removal of `get_maxfd()` means the `resource` module is no longer required (which is not available on Windows) and so helps with #524.
> Remove dead code found using vulture

- gunicorn/config.py
- tests/test_config.py
because we define `type=int` in `umask` , error occur in this line of `argparse`:
[https://github.com/bewest/argparse/blob/master/argparse.py#L2248](https://github.com/bewest/argparse/blob/master/argparse.py#L2248).
thus i change umask type to auto_int function.
> fix non-decimal values problem in `umask` config.(issue 1325)

- gunicorn/sock.py
> Catch errors setting SO_REUSEPORT

- gunicorn/sock.py
In python3 the exception object is not iterable and must use either the `args` attribute or in this case `errno` (equivalent to `.args[0]`).
> Fix "TypeError: 'OSError' object is not subscriptable" in py3

- gunicorn/config.py
- gunicorn/reloader.py
- gunicorn/workers/base.py
I quickly added an option which is implemented but not exposed in the command line.
Would something like this be excepted? If yes I'll add the documentation for the command line option.
/cc @tilgovi (author of ``gunicorn/reloader.py``)
> new --reload-extra-file option

- gunicorn/config.py
The current documentation makes a reader believe that the setting is ignored if the worker type is not Gthread. That is not the case since if the worker is `sync`, a `threads` setting of > 1 sets the worker type to `gthread`.
I know this was probably done to support running gunicorn as `gunicorn --threads=4` and actually have threads even though the default worker is `sync`, but it can be confusing if running `gunicorn --worker-class sync --threads 4` and expecting the parameter will be ignored.
> Document selection of 'gthread' worker if sync && threads > 1

- gunicorn/glogging.py
Default to sock_type None, unless explictly overridden, and explain how this covers both options
> parse_syslog_addr sock_type default

- docs/source/design.rst
- docs/source/settings.rst
- gunicorn/config.py
Related to: https://github.com/benoitc/gunicorn/issues/1194
As per https://github.com/benoitc/gunicorn/issues/1194#issuecomment-239917723 am I'm correct in stating that `sync` worker just doesn't support keep-alive, even if you try setting the header manually?
> doc: Keepalive missing in sync worker and value recommendation

- appveyor.yml
Currently everything but the prospector lint job fails, however having CI set up makes it easier to see what work remains for #524.
Fixes #1467.
> Enable CI testing on Windows using Appveyor

- docs/README.rst
- docs/source/2010-news.rst
- docs/source/configure.rst
- docs/source/deploy.rst
- docs/source/design.rst
- docs/source/faq.rst
- docs/source/install.rst
- docs/source/instrumentation.rst
- docs/source/run.rst
- Fix dead link to Gaffer in docs
- Update links to reduce HTTP redirects (e.g. http->https, with/without www subdomains, trailing slashes)
> Update docs links

- docs/source/install.rst
Update Debian installation instructions as two years passed after #1112 and 'stretch' Debian 9 was released.
> Update Debian installation instructions

- THANKS
- gunicorn/app/base.py
- tests/config/test_cfg_alt.py
- tests/test_config.py
I also sorted THANKS.md to follow CONTRIBUTING.md.
> Fix #1576 - config file/module in GUNICORN_CMD_ARGS

- docs/source/2016-news.rst
See https://github.com/benoitc/gunicorn/pull/1205/files for correct spelling of environment variable.
> docs: Fix typo in environment variable name

- gunicorn/workers/ggevent.py
I found this by mixing flask-websocket in a flask app -- the parsing logic here leaves whitespace in the header values (including \r\n) so it's not suitable for extracting headers into logs.
> Fix broken header parsing in logging

- gunicorn/arbiter.py
(deleted) tmp files left around #1327
> Update arbiter.py to not leave tmp files around (fix #1327)

- gunicorn/config.py
- tests/test_config.py
Fix umask option bug. [issue_1622](https://github.com/benoitc/gunicorn/issues/1622l)
> Fix umask option bug(issues#1622)

- gunicorn/app/base.py
- gunicorn/app/pasterapp.py
- gunicorn/app/wsgiapp.py
The config may be specified as a Python module, in which case we want
to ensure that the Python path is fixed up properly before we try to
load it. That means we should follow symlinks and add the current working
directory before and after the configuration is loaded.
Fix #1349
> Set CWD and Python path before and after config

- gunicorn/config.py
- gunicorn/glogging.py
Taking over #1110 as per the OP request.
> Support Dictionary Config setting.

- docs/source/design.rst
- docs/source/news.rst
- docs/source/run.rst
- docs/source/settings.rst
- examples/frameworks/flaskapp_aiohttp_wsgi.py
- gunicorn/config.py
- gunicorn/workers/gaiohttp.py
> Deprecate gaiohttp worker and document alternatives

- gunicorn/workers/ggevent.py
The gevent worker assumes sockets are running in blocking mode.  The current code forces the listening socket into blocking mode [here](https://github.com/benoitc/gunicorn/blob/19.7.1/gunicorn/workers/ggevent.py#L98).  But the connected socket is not forced to blocking mode.  Therefore if other code has set the default socket timeout with a call to `setdefaulttimeout` it will be set as the connected socket's timeout in the gevent initialization code [here](https://github.com/gevent/gevent/blob/v1.2a2/src/gevent/_socket3.py#L90).
The gevent worker relies on the keepalive timeout to close idle connections.   Setting the default timeout below the keepalive timeout causes the worker to run in a undefined mode.  I believe this may fix the issues in …
> Force gevent connected socket to blocking mode

- docs/source/settings.rst
- gunicorn/config.py
- gunicorn/sock.py
I'm open to opinions as to whether ``SO_REUSEPORT`` should be the default or not.
Also, would appreciate some advice about unit testing this change.
> Make SO_REUSEPORT Optional

- gunicorn/util.py
On MacOSX (tested on Sierra 10.12) setgid(getgid()) causes subsequent calls to issetugid to return true, even though the operation is a no-op.  Kerberos examines issetugid on OSX and ignores KRB5_KTNAME on true.  This makes it impossible to use gunicorn in a kerberos enabled app that relies on keytabs.
> Avoid needlessly triggering true return from issetugid on MacOSX

- gunicorn/workers/gthread.py
> Avoid 'Connection refused' when using gthread with keep-alive

- docs/source/install.rst
- docs/source/settings.rst
- gunicorn/config.py
- setup.py
> Add extras_require for various worker types

- README.rst
As suggested in https://github.com/benoitc/gunicorn/issues/1634:
> Pypi seems to be still at 19.7.1 https://pypi.python.org/pypi/gunicorn
As a side thought could the README.md be made to have stable version number?
going trough pypi to check what is the current release feels bit funky, or perhaps I'm missing some obvious version number displayed somewhere 😕
Preview:
Also upgrade the Travis badge to SVG which looks better, and whilst we're here, update HTTP links to HTTPS.
> Add PyPI badges to README

- gunicorn/glogging.py
Fix #1739 
Reopen log files by using FileHandler's method,  so that gunicorn can be compatible with different handler.
I tested this change on my handler, gunicorn reopen files as expected. Also tested by tox, and succeeded in py26, py27, py35 on my server .
> Optimize the reopen_files by using FileHandler's method: close & _open

- gunicorn/glogging.py
Config option `disable_access_log_redirection` does not exist
> Fix issue #1768

- docs/source/deploy.rst
The sample as-is was not clear about what file the configuration was to go in. 
This sample is to go into nginx.conf, but nginx as of 20180516 has nginx.conf + conf.f/default.conf
This sample overrides all that into the single file so being specific is better.
> Labeled the name of the file in the sample

- gunicorn/glogging.py
Hey there friends, this fix relates to issue #1793 
Thanks heaps
Fotis
> Ensured that default logging streams are prefixed with ext:// so they work correctly

- docs/source/news.rst
- gunicorn/workers/base.py
> Fix AttributeError when --reload was not passed

- gunicorn/reloader.py
I noticed that `--reload` was taking up a decent amount of CPU time using the classic polling reloader. Precompiling the .pyc/.pyo extensions regex like we do in other modules helped. Linux users with inotify are unlikely to notice a difference.
If we wanted to optimize further, the `sub` method could be saved in a module var, but I think readability starts to decline.
> Minor reloader optimizations

- docs/site/index.html
Page stopped working on new browsers 
https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content
output from FF console:
Blocked loading mixed active content “http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js”
gunicorn.org
Loading failed for the <script> with source “http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js”. gunicorn.org:182
ReferenceError: $ is not defined
> Fixed jQuery not using https

- docs/source/faq.rst
FYI I got a very minor perf boost on superficial local testing on ubuntu bionic using `wrk`, but notably I was getting 2 or 3 read errors when not using `/dev/shm`
> [closes #1863] Docs: Add /dev/shm as a convenient alternative to making your own tmpfs mount in fchmod FAQ

- gunicorn/http/message.py
- gunicorn/sock.py
- tests/test_sock.py
Some systems report UNIX socket addresses as bytes while others will
report it as a unicode string type. This patch improves socket type
detection code to support both.
Fix #1861
> Support str and bytes for UNIX socket addresses

- gunicorn/arbiter.py
`keys()` is a dynamic view under Python 3 and these dictionaries are not modified concurrently, so we don't need call the dict keys method anymore. And using `len(dict)` is more pythonista to get dict count by the way
> Remove unnecessary call to dict keys method

- gunicorn/_compat.py
The raw open call in `_compat:execfile_` did not close the file handle.
Switch to using pathlib to read the raw bytes.
Logs:
```
Oct 02 05:04:38 ubuntu-bionic systemd[1]: Started Gunicorn server for hyperbola django.
Oct 02 05:04:38 ubuntu-bionic gunicorn[12173]: /hyperbola/app/releases/20181002050352/venv/lib/python3.6/site-packages/gunicorn/_compat.py:71: ResourceWarning: unclosed file <_io.BufferedReader name='/hyperbola/app/current/gunicorn.py'>
Oct 02 05:04:38 ubuntu-bionic gunicorn[12173]:   code = compile(open(fname, 'rb').read(), fname, 'exec')
Oct 02 05:04:38 ubuntu-bionic gunicorn[12173]: [2018-10-02 05:04:38 +0000] [12173] [INFO] Starting gunicorn 19.9.0
Oct 02 05:04:38 ubuntu-bionic gunicorn[12173]: [2018-10-02 05:04:38 +0000] [12173] [INFO] Listening at: …
```
> Fix unclosed file warning when reading a python config module

- .travis.yml
- appveyor.yml
This PR updates the Travis config to do the following:
* Make tests against Python 3.7 required to pass
* Drop tests against Python 3.6-dev
* Test against 3.8-dev instead (but make it an allowed failure)
It also similarly updates the Appveyor config:
* Make tests against Python 3.5 required to pass
* Make tests against Python 3.6 required to pass
* Test against Python 3.7 (and make it required to pass)
> Update CI configs for 3.5, 3.6, 3.7 and 3.8

- docs/source/deploy.rst
The systemd files recommended in the docs do not work. The socket file disappears after the first request, or after the service is restarted. 
This commit updates the systemd files to include the correct settings
Fixes: https://github.com/benoitc/gunicorn/issues/1524
> Fixed systemd documentation to properly setup gunicorn unix socket

- docs/source/settings.rst
- gunicorn/config.py
Add a bit of detail on how to put headers and environment variables in the access log.
As you'll see, settings.rst is updated via `make -C docs html`.
> Clarify log format usage of header & environment.

- appveyor.yml
It's fine that AppVeyor has been activated for the repo, and I'm sure that will be appreciated by anyone working on Windows support (#524) in any form.
For now Windows support seems somewhat distant (although there may be great leaps) - in the interim it will be a little tiresome to have AppVeyor mark all PRs and branch builds as bad due to Windows platform failures.  You see it now in any new or rebased PR on master.
This PR marks all but the `lint` AppVeyor builds as members of `allow_failures`.  Each platform/version still runs and you can click-through to see the status and console/errors, but it won't mark the build as bad.  This makes sense because Windows is not currently supported, and the build is therefore expected to fail there.
When these builds are passing, this change can be …
> AppVeyor: allow failures, run lint using Python 3.7

- THANKS
- gunicorn/config.py
- tests/test_config.py
I found that I had this old contribution lying around without a matching PR.
Fixes #1454 , fixes #1114 .  /cc @tilgovi .
> Ssl version named constants

- docs/source/custom.rst
I had a use case where I needed to be able to standardize how our servers are running, but the application code could vary wildly within the scope of existing as a WSGI app ala flask or django. This had to happen within a PEX context, and I was able to get it working nicely and reliably after digging through the Gunicorn source to find this approach. Now I've got a happy little scaffold for wsgi apps that is standard for our company that works well PEX files by including Gunicorn in the build, but it was a real pain to figure this out, and it would've save me a day or two of researching in circles if this was mentioned somewhere
Hope this matches appropriate formatting, I checked CONTRIBUTING and it didn't mention much about docs and Github isn't rendering the preview quite right
> Docs: serving WSGI app modules from Gunicorn

- THANKS
- docs/source/news.rst
- docs/source/run.rst
- docs/source/settings.rst
- gunicorn/config.py
- gunicorn/sock.py
- gunicorn/socketfromfd.py
- gunicorn/util.py
- tests/test_config.py
- tests/test_util.py
This is an initial try to fix #1107.
@benoitc Which kind of tests do you expect here? I couldn't find much in the testsuite; I'll add parsing tests for `fd://` but is there anything else I should add?
This commit currently vendors https://github.com/tiran/socketfromfd/blob/master/socketfromfd.py from @tiran -- Christian: Would you be okay with this approach (and relicensing under the gunicorn license) or would you like use to use the pypi package (I'd rather vendor given that gunicorn has no dependency).
> Added support to bind to open file descriptors.

- setup.py
We rely on setuptools' pkg_resources in a few places so we declare our
dependency so that packaging and installation tools work.
Fixes #1716
> Declare our setuptools dependency.

- docs/source/deploy.rst
- gunicorn/arbiter.py
- gunicorn/systemd.py
roughly based on sd_notify() from systemd and https://github.com/bb4242/sdnotify
only implements `READY=1` and `STATUS=Gunicorn arbiter booted` of the
protocol in the arbiter. in the future, reloads can be notified, and
possibly also other statuses.
see https://www.freedesktop.org/software/systemd/man/sd_notify.html for
more info
sd_notify() is a noop when not run in a systemd service (i.e
NOTIFY_SOCKET environment variable is not set)
> add systemd sd_notify support

- docs/source/deploy.rst
There's no need for PIDFile=, especially not for `Type=notify` (or simple) services.
systemd knows the correct pid of the process it manages.
No need for the `--bind` option either, since gunicorn supports the
LISTEN_FDS environment variable and will use all of the sockets that systemd
provides. This way, it's also more flexible, since we can specify several
sockets in a .socket unit.
The .socket unit should specify User=www-data so that nginx can connect to the socket.
The service (gunicorn process) will inherit the file descriptor so it
doesn't even need permissions for the socket (it's nginx which needs
permissions).
tmpfiles.d is not needed.
replace ExecStop=/bin/kill with KillMode=mixed
ps.
this is the same change with https://github.com/benoitc/gunicorn/pull/1896 which was …
> documentation: update systemd deploy unit examples

- docs/source/settings.rst
- gunicorn/config.py
Quick one - I noticed this typo I made in new text `ssl_version` option.
> Fixed typo in ssl_version doc, TLSv2 -> TLSv1_2 (TLS 1.2).

- .travis.yml
- tox.ini
To save time to fix docs formatting (#1592, #1597), add [restructuredtext_lint](https://github.com/twolfson/restructuredtext-lint) to test.
At this moment there's no way to ignore extended directives and roles for Sphinx in restructuredtext_lint CLI and so this PR includes a workaround to skip the following errors:
```
2 ERROR Unknown directive type "highlight".
2 ERROR Unknown directive type "literalinclude".
2 ERROR Unknown directive type "toctree".
14 ERROR Unknown directive type "versionadded".
7 ERROR Unknown directive type "versionchanged".
1 ERROR Unknown interpreted text role "class".
6 ERROR Unknown interpreted text role "doc".
148 ERROR Unknown interpreted text role "issue".
2 ERROR Unknown interpreted text role "pr".
21 ERROR Unknown interpreted text role "ref".
```
Blocked …
> Add restructuredtext_lint to test

- docs/source/settings.rst
- gunicorn/config.py
- tests/test_ssl.py
Remove the default value `'TLSv1'` for `--ciphers` which *weakens* security over Python's defaults.
Setting to `None` appears to work everywhere. In one case (_gaihttp.py) it's already special-cased. Everywhere else it is passed to `ssl.wrap_socket()`, where `ciphers=None` is allowed, to use the default cipher set.
Fixes #1966.
> Use Python's default SSL cipher list by default

- docs/source/run.rst
- gunicorn/app/pasterapp.py
- gunicorn/app/wsgiapp.py
- setup.py
Remove the `gunicorn_paster` command. With the `--paste` option to the
`gunicorn` command, Gunicorn will no longer read the server section of
the configuration. Instead, server configuration must be done with
Gunicorn configuration files, command line switches, and environment
variables.
The use of Gunicorn as a Paste Deployment server factory is no longer
deprecated. It allows specifying `host` and `port`, as well as `bind`,
but is otherwise more strict with options than in the past. Rather than
ignoring unknown options it will raise an error.
Close #1189
> Simplify Paste Deployment integration

- gunicorn/workers/gthread.py
Commits e974f305 and 78208c8c removed support for Python 2 and Python
<3.4 respectively so the conditional logic for importing
`concurrent.futures` is no longer necessary as it has been part of the
standard library since Python 3.2.
> Simplify futures import

- gunicorn/workers/gthread.py
Move ThreadPoolExecutor() creation into it's own method so it is easier
to override when subclassing.
> Move ThreadPoolExecutor() creation into own method

- examples/test.py
- gunicorn/http/wsgi.py
- tests/test_http.py
This commit reverts one aspect changed by 5f4ebd2eb2b08783a5fbefe79d09fcb3fc1fbc73 (#1151);
header-values are again encoded as latin-1 and not ascii. Test is restored but uses
a latin-1-mappable test-character, not a general utf8 character.
Fixed #1778.
Per question in #791, is there a best way to automate the test?
> Encode header values using latin-1, not ascii

- THANKS
- docs/source/settings.rst
- gunicorn/config.py
- gunicorn/instrument/statsd.py
- tests/test_statsd.py
The datadog hosted metrics service uses a slightly forked statsd protocol in order to add arbitrary key/value tags to metrics. This PR allows the user to set a static list of datadog tags to send along with statsd metrics. I would like to be able to e.g. send the tags "app_name:my_awesome_web_app" and "stage:prod" along with my stats. This lets you easily create dashboard that only show stats from the prod stage.
> optionally send datadog tags with statsd

- docs/source/settings.rst
- gunicorn/config.py
- setup.py
Content refers to the `"extra_require"` field from `setuptools.setup`.
This field is actually `"extras_require"`. I have made this mistake myself before.
[Setuptools Documentation](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies)
- [Image Source](https://setuptools.readthedocs.io/en/latest/setuptools.html)
> Fix setup field typo

- gunicorn/util.py
See https://docs.python.org/3/library/functions.html#__import__
```
$ python -V
Python 3.7.2
$ gunicorn examples.echo:app
[2019-05-20 23:09:16 +0900] [26697] [INFO] Starting gunicorn 19.9.0
[2019-05-20 23:09:16 +0900] [26697] [INFO] Listening at: http://127.0.0.1:8000 (26697)
[2019-05-20 23:09:16 +0900] [26697] [INFO] Using worker: sync
[2019-05-20 23:09:16 +0900] [26700] [INFO] Booting worker with pid: 26700
```
> Avoid using __import__ and eval

- gunicorn/app/base.py
- gunicorn/util.py
Remove `util.import_module`. I think this is the last cleanup around module importing functionalities.
refs #2046 and #2043
> Remove util.import_module

- tests/test_arbiter.py
- tests/test_http.py
- tests/test_pidfile.py
- tests/test_sock.py
- tests/test_systemd.py
unittest.mock is new in version 3.3
https://docs.python.org/3/library/unittest.mock.html#module-unittest.mock
> Refactor imports of unittest.mock

- gunicorn/workers/gtornado.py
Hi @benoitc,
Following https://github.com/the-benchmarker/web-frameworks/pull/1012, this `PR` fix some backwards incompatibility of `tornado` **worker** for last release of https://github.com/tornadoweb/tornado
@see https://github.com/tornadoweb/tornado/blob/master/docs/releases/v6.0.0.rst
Regards,
> Fix compatility with tornado 6

- gunicorn/glogging.py
- tests/test_logger.py
- tests/test_util.py
According RFC-7617 (inherited from RFC-2978) schema and parameter names are handled
case insensitively:
```
Note that both scheme and parameter names are matched case-
insensitively.
```
Signed-off-by: Martin Bašti <mbasti@redhat.com>
> Logging: Handle auth type case insensitively

- gunicorn/workers/workertmp.py
When Gunicorn is configured to change the effective user or group of the
worker processes, it changes the owner and group fo the the temporary
files used for interprocess communication.
With this change, Gunicorn does not change the owner or group of the
files if the worker processes will run as the current effective user and
gorup. This change avoids calling chown when it is not necessary, which
may allow Gunicorn to be used in environments that restrict use of the
chown syscall.
Relates to #2059.
> Avoid unnecessary chown of temporary files

- docs/source/custom.rst
- docs/source/install.rst
- setup.py
This allows you to specify that you want ``setproctitle`` installed so that ``gunicorn`` can set meaningful process names at install time (``pip install gunicorn[gevent,setproctitle]``) or in a requirements file (``gunicorn[gevent,setproctitle]==19.9.1``). Fixes issue #2085.
> Add setproctitle to extras_require

- .travis.yml
- setup.py
- tox.ini
One of the advantages `gunicorn` has is PyPy3 support (see uWSGI issue https://github.com/unbit/uwsgi/issues/869). This PR adds CI testing for PyPy3 so users can be confident that support does not regress.
> Test under PyPy3

- gunicorn/http/wsgi.py
When integrating with WebApp2 3.0.0b1 (latest, Python 3) and WebOb 1.8.5 (latest), header value was being passed as byte string and resulted in the exception: "TypeError: cannot use a string pattern on a bytes-like object". Regex search fails due to this value. Current gunicorn implementation parses the value as string, but only after regex search. Changing the casting of value to string before regex search ensures this exception will not occur. This change fixes integration with these libraries.
> Ensure header value is string before conducting regex search.

- .pylintrc
- gunicorn/http/message.py
- gunicorn/reloader.py
- gunicorn/util.py
- gunicorn/workers/gthread.py
> Add some lint errors to .pylintrc disable list (#2123)

- gunicorn/workers/workertmp.py
Fix https://github.com/benoitc/gunicorn/issues/2091
> Fix fdopen RuntimeWarning in 3.8

- gunicorn/workers/geventlet.py
- gunicorn/workers/ggevent.py
Fixes #1925 and fixes #2170.
This is one possible way to do it.
> Capture os.sendfile before patching in gevent and eventlet workers.

- docs/source/run.rst
- gunicorn/util.py
- tests/support.py
- tests/test_util.py
Use `ast.parse` to validate that the string passed to the CLI is either an attribute name or a function call. Use `ast.literal_eval` to parse positional and keyword arguments to the function. Call the function to get the real application.
fixes #2159 
Todo:
> load application from factory function

- gunicorn/socketfromfd.py
This patches the `fromfd` code in `socketfromfd` by grabbing the correct symbol under SmartOS (SunOS).  
The patch is pretty straightforward, basically switching on the OS to determine what the symbol is likely to be.  If need be, I could put a try block around the original libc.getsockopt and then fall back to looking for `_so_getsockopt`, if that's preferred in this codebase.
> Fix for #2184 solaris erroring out on getsockopt

- THANKS
- gunicorn/reloader.py
- gunicorn/workers/base.py
When launching Gunicorn with the `--reload` option, workers will start the Reloader and then load the wsgi app. This is problematic because user files are loaded when the wsgi app is loaded, and the reloader depends on the user files to be loaded so that it can watch them.
So when the Reloader starts, it isn't watching any user files. This isn't an issue when using the default polling reloader as it updates what files it is watching every time it polls but this is an issue with the inotify reloader.
This PR makes sure the reloader is started after wsgi app has been loaded so that the InotifyReloader is able to pickup and watch the proper files/folders.
> Start the reloader after the wsgi app has been loaded.

- gunicorn/http/message.py
- gunicorn/http/wsgi.py
Sometimes both TRANSFER-ENCODING=chunked and CONTENT_LENGTH are set. Since gunicorn prioritise (following the HTTP1.1 spec) chunked encoding we should make sure in this case to signal to th application that the input is terminated by the server.
Without the change gunicorn were always setting wsg.input_terminated to False when a CONTENT_LENGTH header was present ignoring that Gunicorn was afaik handling the termination.
> fix wsgi.input_terminated

- gunicorn/socketfromfd.py
- gunicorn/util.py
find_library('c') doesn't work in Alpine Linux. This happen because musl has a simpler implementation of libc.
This patch fix it by extending ctypes.util.find_library to search the libs using LD_LIBRARY_PATH.
Patch is based on https://github.com/python/cpython/commit/e3f67780aab24401a50af64e688d38c24ee41ad0
See also https://bugs.python.org/issue21622
fix #2160
> fix gunicorn when used with musl libc

- gunicorn/config.py
- tests/test_config.py
It's sometimes helpful to be able to trivially dump all the config values
for debugging purposes. This commit defines a repr for that. See #2075
> Add a __repr__ to config to include its value

- gunicorn/socketfromfd.py
- gunicorn/util.py
Resolves #2194 to allow gunicorn on IBM i (and AIX) platform with Python 3.6 and earlier
> fix IBM i 'missing libc' failure

- .travis.yml
- README.rst
- docs/source/index.rst
- gunicorn/__init__.py
- gunicorn/app/base.py
- setup.py
- tox.ini
current import of the config module doesn't add the `__file__` attribute to the imported module. 
Fix is done by loading the module as suggested in the Python docs winds up setting __file__ as expected (https://docs.python.org/3/library/importlib.html#importing-a-source-file-directly).
Since this change only work on Python >= 3.5 and Python 3.4 is unsupported we also remove its support.
fix #2182
> fix attributes when importing config module

- docs/source/configure.rst
- gunicorn/app/base.py
This change make it clear what is configuration file for Gunicorn.
Using a filename with an extension different than a python extension
was never supported. Also it gives us some room for a proper config file.
fix #2198
> config file extension should be a python extension

- setup.py
Following 441977f57c628dffb903ce66cf50dcba92c1872e, make setup require >=3.5 .
> Bumped py3 min version in setup.py to 3.5 (was 3.4)

- docs/source/run.rst
Extra `:` was causing the syntax highlighting to mess up, resulting in the docs containing the `..code-block:: text` markup. Fix it by removing the offending colon
> Fix sample command syntax highlighting in run.rst

- gunicorn/app/base.py
- gunicorn/arbiter.py
- gunicorn/config.py
- gunicorn/glogging.py
- gunicorn/http/message.py
- gunicorn/http/wsgi.py
- gunicorn/instrument/statsd.py
- gunicorn/pidfile.py
- gunicorn/reloader.py
- gunicorn/util.py
- gunicorn/workers/base.py
- gunicorn/workers/base_async.py
- gunicorn/workers/ggevent.py
- gunicorn/workers/gthread.py
- gunicorn/workers/sync.py
- gunicorn/workers/workertmp.py
- tox.ini
Adds pycodestyle (latest version; 2.4.0 at this moment) in CI now, while prospector was deprecated by solo pylint (#1678).
In general, this PR follows the default rules of pycodestyle 2.4.0. The following errors/warnings, however, are ignored at this moment to avoid the delay of merging with unintentional discussion as this PR would be just the first step:
- E129
- W503
- W504
- W606
Replaces #1600
> Enable pycodestyle

- gunicorn/reloader.py
I ran into an error when running gunicorn with the reload option. 
When debugging it appeared that it was caused by a file that was caused in the working dir of gunicorn.
With the previous code, adding a watcher for a file located in the working directory generates an empty dirname, resulting in the following error:
```
Exception in thread Thread-1:
File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
self.run()
File "/usr/lib/python3.8/site-packages/gunicorn/reloader.py", line 105, in run
self._watcher.add_watch(dirname, mask=self.event_mask)
File "/usr/lib/python3.8/site-packages/inotify/adapters.py", line 98, in add_watch
wd = inotify.calls.inotify_add_watch(self.__inotify_fd, path_bytes, mask)
File …
```
> add os.path.abspath() in dirname generation of the reloader

- setup.cfg
Since Python 2 support has been dropped, we should no longer build and publish a universal py2/py3 wheel.
Note that this will change the wheel filename, and the new filename will by-default change from:
`gunicorn-20.0.4-py2.py3-none-any.whl`
to
- `gunicorn-20.0.4-cp35-none-any.whl` if built with current oldest-supported cpython
- `gunicorn-20.0.4-cp38-none-any.whl` if built with the current and supported latest cpython
So if there are any known dependencies on the wheel filename (shouldn't be), then we should be aware of that.  Probably not release-note worthy?
This reverts commit 765b8ab48b6fb991eeb9bcf4f60c0cba6f48359f .
> Don't build universal wheel, as Python 2 support has been removed

- docs/source/install.rst
This might be the final legit 3.4->3.5 mention update.  There's a 3.4 in the `docs` build requirements readme, but docs can still be built with 3.4 if you really want to ... maybe we should bump that anyway.
> Updated requires Python to >= 3.5

- .travis.yml
- gunicorn/http/wsgi.py
- gunicorn/workers/geventlet.py
- gunicorn/workers/ggevent.py
- requirements_test.txt
- setup.py
- tests/workers/test_geventlet.py
- tests/workers/test_ggevent.py
- tox.ini
Fixes #2223.
Unfortunately, eventlet doesn't implement GreenSocket.sendfile, so we have to do it for it.
Add gevent and eventlet to tox.ini and add tests to make sure we can at least import the workers. Some tests that this actually functions would be nice...
Update the gevent and eventlet setup extras to require the versions that are enforced in their worker modules.
> Use socket.sendfile() instead of os.sendfile().

- gunicorn/__init__.py
- gunicorn/http/wsgi.py
while we still want to know which server is running to ease operation, the version was giving too much information on the installation, so let's remove it.
> remove version from the Server header

- docs/source/settings.rst
- gunicorn/config.py
- gunicorn/glogging.py
I tested this code locally in my docker container and this is a sample output:
`ResponseTime:1|ResponseTime:1137|ResponseTime:1137324`
to this access_log_format:
`ResponseTime:%(T)s|ResponseTime:%(M)s|ResponseTime:%(D)s`
> Add milliseconds option to request_time in access_log

- gunicorn/util.py
This is just a bit of dead code discovered while investigating #2247 .
The code was added to fix #2160 for socketfromfd.py which was itself [removed later](https://github.com/benoitc/gunicorn/commit/67cb62099c27de00cf80b30e37a7617c2c0ec2ed#diff-cd1a6450c95ae0e121da73674dc3e908).
> Remove dead code: find_library and _findWalk_ldpath

- docs/source/configure.rst
- docs/source/settings.rst
- gunicorn/config.py
As described in #2247, this documents the effect of the `$PORT` environment variable on the default value of `--bind` and documents the impact and priority of the environment variables in the configuration overview.
~The dead code using the environment variable `LD_LIBRARY_PATH` is also removed.~
> Document environment variables and $PORT

- examples/websocket/gevent_websocket.py
- examples/websocket/websocket.py
There is a small typo in examples/websocket/gevent_websocket.py, examples/websocket/websocket.py.
Should read `convertible` rather than `convertable`.
> Fix simple typo: convertable -> convertible

- gunicorn/workers/ggevent.py
We've had really terrible tail latencies with gevent and gunicorn under load.
Inspecting our services with strace we see the following:
```
23:11:01.651529 accept4(5, {sa_family=AF_UNIX}, [110->2], SOCK_CLOEXEC) = 223 <0.000015>
..{18 successful calls to accept4}...
23:11:01.652590 accept4(5, {sa_family=AF_UNIX}, [110->2], SOCK_CLOEXEC) = 249 <0.000010>
23:11:01.652647 accept4(5, 0x7ffcd46c09d0, [110], SOCK_CLOEXEC) = -1 EAGAIN (Resource temporarily unavailable) <0.000012>
23:11:01.657622 getsockname(5, {sa_family=AF_UNIX, sun_path="/run/gunicorn/gunicorn.sock"}, [110->30]) = 0 <0.000009>
23:11:01.657682 recvfrom(223, "XXX"..., 8192, 0, NULL, NULL) = 511 <0.000011>
..{16 calls to recvfrom}...
23:11:01.740726 recvfrom(243, "XXX"..., 8192, 0, NULL, NULL) = 511 <0.000012>
23:11:01.746074 …
```
> Set `max_accept` on `gevent` worker-class to 1 when workers > 1

- gunicorn/reloader.py
- gunicorn/workers/base.py
- tests/test_reload.py
This PR contains a test and fix for #2244 
The "chicken and egg problem" with the (inotify-based) reloader depending on the wsgi app to be loaded first, and `load_wsgi` depending on the reloader to be present is solved by initializing the reloader first, but only starting it after the wsgi app was loaded.
I've added an integration test that runs `gunicorn --reload` in a tmpdir, replaces the WSGI app and checks for changes in the HTTP response via a unix domain socket. In order to not slow down the tests too much, I've made the default poll interval for the poll-based reloader (1 second) overridable via an (undocumented) [environment variable](https://github.com/benoitc/gunicorn/pull/2249/commits/f1f0d011aec16adcb7b28b7fb5b0f3bb391de2fe). I hope this is OK.
Initially, the test was very …
> Issue 2244

- docs/source/configure.rst
- docs/source/settings.rst
- gunicorn/app/base.py
- gunicorn/config.py
- tests/test_config.py
Implementation of #2052. WIP for review.
```console
$ gunicorn --print-config foo
access_log_format                 = %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
accesslog                         = None
backlog                           = 2048
bind                              = ['127.0.0.1:8000']
ca_certs                          = None
capture_output                    = False
cert_reqs                         = 0
certfile                          = None
chdir                             = /Users/rcoup/code/gunicorn
check_config                      = False
child_exit                        = <ChildExit.child_exit()>
ciphers                           = None
config                            = None
daemon                            = False
default_proc_name …
```
> Add --print-config option to print the resolved configuration

- gunicorn/workers/gthread.py
when `gunicorn` works in the `gthread` mode, it does not close the connection properly. Many RST packets are generated, and will cause many 502 errors.
**Background**
let's say we have a load balancer (ELB) and a gunicorn server(`gthread` mode).
ELB maintains a persistent connection, it will send requests very frequently.
Gunicorn processes the requests, add the counter  and return response.
after working for a while, we find many RST packets received in ELB(captured by tcpdump).
and it cause many 502 errors.
**Problem**
Gunicorn closes the socket, but meanwhile packets are received in the socket.
**Reason**
1. line 241
a. in multithread mode, all threads share the same variable `self.nr`. 
b. assume that `max_requests` is 100. if thread1 reads it as 98, thread2 reads it as 100 and …
> Upgrade gthread worker  when behind load balancer

- gunicorn/workers/base_async.py
- gunicorn/workers/gthread.py
Fix graceful shutdown behavior so that clients receive notice to close
the connection.
After #2304 and the follow-up in ebb41da, Joe Kemp noticed that, while
the new behavior would successfully indicate a connect close after
hitting the maximum request limit for a worker during graceful shutdown,
the worker would not indicate a connection close if if it had not hit
the maximum request limit.
This change ensures that the worker exits gracefully when hitting the
request limit and also indicates to clients that the connection should
close once the shutdown begins.
> Disable keepalive during graceful shutdown

- docs/source/settings.rst
- gunicorn/config.py
A follow-up to #2292, adding the same description to `gunicorn/config.py` as well.
Also adds an additional section that seems to be missing from `docs/source/settings.rst` which as automatically added when I built the docs.
> Update settings docs

- gunicorn/__main__.py
✨ Add support for `python -m gunicorn`.
This just adds a simple `__main__.py` replicating the script defined in `setup.py`.
That adds support for `python -m gunicorn`, as described [here in the Python docs](https://docs.python.org/3.8/library/__main__.html).
It is useful when `python` or equivalent is available as a command but `gunicorn` is not, even though it is installed and available to import. And where the idea is still to call it from the CLI and not importing and running from code... :man_shrugging: 
I know that sounds contrived, but the specific use case is Pex: https://pex.readthedocs.io/
It is based on "zip applications" from this [PEP 441](https://www.python.org/dev/peps/pep-0441/).
So, it would be called like:
```console
$ ./some-binary-pex-file -m gunicorn
```
> ✨ Add support for python -m gunicorn

- gunicorn/workers/gtornado.py
When running the WSGI of Django, you need to wrap it with WSGIContainer. Otherwise, the following error will be caused:
```
ERROR:tornado.application:Uncaught exception
File "/usr/local/lib/python3.7/site-packages/tornado/http1connection.py", line 273, in _read_message
delegate.finish()
File "/usr/local/lib/python3.7/site-packages/tornado/httpserver.py", line 280, in finish
self.request_callback(self.request)
TypeError: __call__() missing 1 required positional argument: 'start_response'
```
I think that in tornado6 and above, as long as it is not a WSGIContainer instance, we should wrap it into WSGIContainer
> fix: repair django wsgi running error

- tox.ini
six.py was removed in https://github.com/benoitc/gunicorn/pull/2083 , there's no need to exclude it from tests.
> Remove reference to six.py

- gunicorn/workers/base_async.py
- gunicorn/workers/gthread.py
- gunicorn/workers/sync.py
A couple of socket operations can fail with ENOTCONN error if the
other side of the connection is not connected anymore. In that case,
let's not crash the whole worker and give a chance to accept new
connections.
In my case, the operation that sometimes fails is a "getpeername()",
which was introduced in b07532be752668be5eb5dbd0a8303abf5c219c99
(v19.8.0). Someone in https://github.com/benoitc/gunicorn/issues/1913
metionned that v19.7.1 was working fine so it matches.
Fixes #1913
> Do not raise and crash worker on ENOTCONN error

- gunicorn/arbiter.py
This happens for example when being OOM killed.
See #2215
> Log a warning when a worker was terminated due to a signal

- docs/source/news.rst
- gunicorn/config.py
There is no support for decoding any dictionary supplied on the command
line. The only way to supply a dictionary logging config is through the
configuration file.
Close #1909.
> Remove the --log-config-dict flag

- docs/source/design.rst
> Typo fixed in the AsyncIO docs

- gunicorn/http/message.py
- gunicorn/http/parser.py
- gunicorn/workers/base_async.py
- gunicorn/workers/gthread.py
- gunicorn/workers/sync.py
- tests/t.py
- tests/treq.py
Avoid calls to getpeername by capturing the peer name returned by
accept.
> Capture peer name from accept

- docs/gunicorn_ext.py
- docs/source/settings.rst
- gunicorn/config.py
I was reading the documentation to configure another application successfully deployed with Gunicorn, and thought the documentation here could be improved a bit for clarity.
* Use code highlighting for the names, to indicate they are the names to use in the Python configuration file.
* Spell out the CLI flags and defaults with "Command line" and "Default" prefixes so it's clear what these are
* Consistently use Python syntax for the defaults, so the types may be more easily understood.
* Split multiple CLI flags with "or" rather than a comma, for clarity and easier copy-paste.
* Improve some descriptions, such as for ``raw_env`` and a header for "Server Hooks".
> Improve settings documentation

- docs/source/custom.rst
There is a typo in custom configuration's page where commands to run a custom app were missing a parameter.
> [Typo] Custom Application Section

- docs/source/settings.rst
The usage of logconifg_dict can be confusing, not only since there is not a clear example on the site now, but also since the documentation of [python's dictConfig](https://docs.python.org/3/library/logging.config.html#logging.config.dictConfig) is minimal. And since you need to know about the specific loggers that gunicorn uses to configure them properly.
> Added a line to the documentation to further explain the use of logconfig_dict.

- gunicorn/config.py
The name for threaded worker is `gthread`, not `threads`.
This fix only affects a startup log message says `Using worker: xxx` when `sync` is used and `threads` greater than 1.
> Fix a naming error for gthread worker

- gunicorn/workers/geventlet.py
Eventlet 0.30.3+ removed `wsgi.ALREADY_HANDLED` breaking public API in just a patch version increase. Sorry.
Issue with ALREADY_HANDLED: https://github.com/eventlet/eventlet/issues/543
Solution with WSGI_LOCAL: https://github.com/eventlet/eventlet/pull/544
It's recommended to use `eventlet>=0.31.0` if one uses websockets, because older versions are vulnerable to DoS attack. https://github.com/eventlet/eventlet/security/advisories/GHSA-9p9m-jm8w-94p2
CI failed in pylint checks on lines I didn't touch.
> eventlet worker: ALREADY_HANDLED -> WSGI_LOCAL

- examples/frameworks/django/testing/testing/apps/someapp/tests.py
> *Deprecated since version 3.1:* The fail* aliases listed in the second column have been deprecated.
https://docs.python.org/3/library/unittest.html#deprecated-aliases
> Replace deprecated unittest alias

- THANKS
- gunicorn/util.py
Alternative to #2727 , see discussion there.
When `gunicorn --daemon` daemonizes the process, prior to this change it was
noted that in the general case (without `-R` / `--enable-stdio-inheritance`), when fd 0
was replaced with /dev/null, the dup2 copy is skipped, and per PEP 446
"Make newly created file descriptors non-inheritable", the result was a stdio
fd </dev/null which was non-inheritable.  As a result, any launched subprocess
did not have an open 0/stdin fd, which can cause problems in some applications.
This change retains the behaviour of opening /dev/null with fd 0, but adds a call
to os.set_inheritable(..) to ensure the fd is inheritable.
The -R branch had different logic but has now been standardised with the general
case.  It was previously opening /dev/null as fd 3 and the …
> Ensure fd 0 stdin </dev/null is always inheritable

- .github/workflows/tox.yml
- appveyor.yml
- tests/workers/test_geventlet.py
- tox.ini
___GitHub Actions test results:___ https://github.com/cclauss/gunicorn/actions
Because Travis CI seems to be on vacation... https://travis-ci.org/github/benoitc/gunicorn
___TypeError: cannot set 'is_timeout' attribute of immutable type 'TimeoutError'___
```
============================= test session starts ==============================
platform linux -- Python 3.10.0, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
cachedir: .tox/py/.pytest_cache
rootdir: /home/runner/work/gunicorn/gunicorn, configfile: setup.cfg, testpaths: tests/
plugins: cov-3.0.0
collected 224 items
[ ... ]
tests/workers/test_geventlet.py F                                        [ 99%]
tests/workers/test_ggevent.py .                                          [100%]
=================================== FAILURES …
```
> GitHub Action to run tox

- .github/workflows/lint.yml
- .github/workflows/tox.yml
- README.rst
This PR splits the new GitHub Actions workflow into two for now - main tox CI/test and linting, since linting currently produces errors, and GH Actions doesn't yet support muting those in any meaningful way for status.
This will provide a clean build badge like so, plus a lint warning badge:
@cclauss ^^ in case you can provide feedback or review.
> Split gh-actions into main/test + lint workflows, replace Travis badges

- gunicorn/util.py
Prevent `setuid` call if the uid is already the right one. In my use case, that allows me starting `gunicorn` with `systemd` straight with the right user, without the permission to do `setuid` syscalls, for some more security.
> Prevent unnecessary setuid call

- README.rst
There was a bit of drama with the freenode network and most channels
have since migrated to libera.chat which is somewhat a spiritual
successor.
> readme: IRC channel has moved to libera.chat

- gunicorn/glogging.py
Fixes https://github.com/benoitc/gunicorn/issues/2784:
```
File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
worker.init_process()
File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/uvicorn/workers.py", line 66, in init_process
super(UvicornWorker, self).init_process()
File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 116, in init_process
self.log.close_on_exec()
File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/gunicorn/glogging.py", line 381, in close_on_exec
for log in loggers():
File "/home/runner/work/galaxy/galaxy/galaxy …
```
> Make loggers function atomic

- gunicorn/arbiter.py
There should be an "error" or "critical" log level here.
> fix LevelLog in Arbiter.run()

- gunicorn/reloader.py
> Set daemon attribute instead of using setDaemon method that was deprecated in Python 3.10

- THANKS
- gunicorn/workers/base.py
This change makes sure that a proper HTTP status code is returned for Request Header Fields Too Large, which fixes #2878.
> Fix HTTP status code for Request Header Fields Too Large

- gunicorn/http/message.py
Hi benotic: 
as I come from uvicorn, and we are running gunicorn + django behind nginx,so I think it is more convenient for people to get the remote address with request.remote_addr than the raw REMOTE_ADDR.I hope you consider my suggestions and approve it.
PS: I use the pre_request to add some request headers based on the remote address.Uvicorn also have a request object,I can get the client ip with request.client.host.
> add attribute remote_addr to req object

- gunicorn/http/wsgi.py
Closes #2669
This issue was caused by Gunicorn not passing the _offset_ parameter to [`socket.sendfile()`](https://docs.python.org/3/library/socket.html#socket.socket.sendfile), which is in turned caused by a deeper issue of the latter being a sloppy wrapper around the [`sendfile`](https://linux.die.net/man/2/sendfile) syscall, which takes an offset pointer parameter, and the default `NULL` values indicates that the current offset should be preserved; however Python's default of 0 means to spool back to the first byte of the file.
@benoitc I don't know what is the best way of adding a test for this -- the majority of current tests run by `tox` seem to be quite simple unit tests, whereas in this case it would probably make more sense to write a system test by spinning up a real Gunicorn …
> Fix sendfile behaviour for open files with non-zero offset

- docs/source/design.rst
https://github.com/benoitc/gunicorn/issues/1493#issuecomment-321461614
> docs: gthread is a sync worker

- docs/source/design.rst
Bitbucket link is unmaintained and now points to GitHub project.
> Fix psycogreen project link

- THANKS
- docs/site/index.html
Update the IRC channel information on the community page on gunicorn.org. The IRC channel is updated in the github readme, but the community page on gunicorn.org doesn't reflect the fact that the chat has moved to libera.chat from freenode.
This pull request aims to ensure that the correct IRC channel is listed on https://gunicorn.org/#community .
> Update irc channel docs

- .github/workflows/lint.yml
- .github/workflows/tox.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
> GitHub Workflows security hardening

- .github/workflows/lint.yml
- .github/workflows/tox.yml
- gunicorn/http/message.py
- tox.ini
1. Updated the CI as part of #2641 to use full matrix for Linux/OSX as well as non-eol python versions
2. Cherry picked c04a30f15546a139d855509b26da6086127dec77 to get tests working
3. Fixed some tox issues preventing tox from working due to v4 changes discussed [here](https://github.com/tox-dev/tox/issues/2730)
4. Adjusted linting to use pylint version where it used to pass (back in travis CI days), if we want to use latest and correct the linting issues as they come we can revert the pylint version lock
I realized a bit too late that you were already working on #2920, so I apologize if you think this seems duplicative.
[🔗 to workflows on my fork](https://github.com/samypr100/gunicorn/actions?query=branch%3Aci-improvements) for this branch
1. pycodestyle doesn't seem to pass in any …
> CI Improvements

- docs/source/configure.rst
- gunicorn/config.py
See #2136 (not a full solution, but at least one more path to understanding added)
I didn't manage to figure out how to add a section description for the "Server Hooks" section (which would be a more complete solution)
> Docs: add link to configuration file

- gunicorn/app/base.py
The timing of [calling sd_notify](https://github.com/benoitc/gunicorn/blob/20.0.4/gunicorn/arbiter.py#L161) is after [daemonizing](https://github.com/benoitc/gunicorn/blob/20.0.4/gunicorn/app/base.py#L217).  Hense, launching will fail eternally if user specify `Type = notify` and `daemon = True`.
User can face this pattern if user already have existing `gunicorn.py` setting file and try to use systemd.  I added warning to make user easilly figure out.
> Warn in the case of bad systemd configuration

- gunicorn/arbiter.py
- Add logging at error level for abnormal worker exit codes.
- Make arbiter shutdown log at error level for abnormal exits.
> More verbose exit logging

- gunicorn/arbiter.py
Fixes #1663 
To test out of memory detection:
```
$ cat g.py
print("eating memory")
a = []
while True:
a.append(bytearray(512000000))
def app(environ, start_response):
pass
$ docker run -it -m 256m --cpus=0.5 -v $PWD:/app python:3.7 /bin/bash
root@8bf8f22c0928:/# cd app
root@8bf8f22c0928:/app# pip install -e .
Obtaining file:///app
Requirement already satisfied: setuptools>=3.0 in /usr/local/lib/python3.7/site-packages (from gunicorn==20.0.4) (50.3.0)
Installing collected packages: gunicorn
Running setup.py develop for gunicorn
Successfully installed gunicorn
root@8bf8f22c0928:/app# gunicorn g:app
[2020-09-12 05:37:48 +0000] [18] [INFO] Starting gunicorn 20.0.4
[2020-09-12 05:37:48 +0000] [18] [INFO] Listening at: http://127.0.0.1:8000 (18)
[2020-09-12 05:37:48 +0000] [18] [INFO] Using …
```
> Add additional logs when worker exits abnormally

- gunicorn/workers/gthread.py
This PR solves issue #2917
It changes the behaviour of the gthread workers. Instead of always reading from tcp sockets opened by a client, the worker only does so when the socket is readable. The main thread does not immediately enqueue new connections anymore to the worker thread queue. Instead it adds new connections to the poller, these connections will be added to the worker thread queue when they are readable.
Please let me know if there are any questions or suggestions for this PR!
> gthread: only read sockets when they are readable (#2917)

- gunicorn/workers/gtornado.py
> fix:  gunicorn run tornado app failed

- docs/source/settings.rst
- gunicorn/config.py
- gunicorn/instrument/statsd.py
- tests/test_config.py
- tests/test_statsd.py
This is a follow-up PR to #2067
It allows gunicorn users to specify a UDS address leveraging the `statsd_host` config option, and reporting metrics through a socket.
I've tried to touch the fewest things possible, added a couple of tests and done a manual test you can reproduce like this:
__datadog.yml__:
```yaml
use_dogstatsd: true
dogstatsd_port: 8125
bind_host: '127.0.0.1'
dogstatsd_non_local_traffic: true
dogstatsd_socket: '/var/run/datadog/dsd.socket'
```
__docker-compose.yml__:
```yaml
version: '3.7'
services:
gunicorn:
image: python:3.8-slim
command:
- python 
- /app/gunicorn/app/wsgiapp.py 
- --bind=0.0.0.0
- --statsd-prefix=test.gunicorn
- --statsd-host=unix:/var/run/datadog/dsd.socket
- test:app
working_dir: "/app/examples"
environment:
PYTHONPATH: "/app"
ports:
- "8000:8000" …
```
> Allow reporting StatsD metrics over UDS sockets

- docs/source/settings.rst
- gunicorn/config.py
- gunicorn/instrument/statsd.py
- tests/test_config.py
Fixes #2066 
Adds a possibility of reporting statsd metrics over a unix domain socket
> statsd over a unix domain socket

- docs/source/settings.rst
The `ThreadWorker` uses `worker_connections` it in its run loop to limit how many connections are accepted.
See https://github.com/benoitc/gunicorn/blob/4ae2a05/gunicorn/workers/gthread.py#L198
> Document that gthread also uses worker_connections

- gunicorn/reloader.py
The signature of `__init__` on the "fall through" InotifyReloader
was missing the extra_files paramater, so specifying the inotify
reload engine on the command line when one did not have inotify
installed would, instead of a nice message about needed inotify
installed would result in the following traceback:
```
[2020-10-30 00:55:43 +0000] [7] [ERROR] Exception in worker process
File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 583, in spawn_worker
worker.init_process()
File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 132, in init_process
self.reloader = reloader_cls(extra_files=self.cfg.reload_extra_files,
TypeError: __init__() got an unexpected keyword argument 'extra_files'
```
I didn't see an easy way to writing a …
> Fix signature of the "fall through" InotifyReloader

- gunicorn/glogging.py
Opening double quote was missed during the recent hence, showing the below error:
auth.split(b":", 1)[0].decode(UTF-8", "replace")
SyntaxError: unterminated string literal (detected at line 472)
> add missing double quote

- docs/source/settings.rst
- examples/example_config.py
- gunicorn/config.py
- gunicorn/sock.py
- gunicorn/workers/geventlet.py
- gunicorn/workers/ggevent.py
- gunicorn/workers/gthread.py
- gunicorn/workers/gtornado.py
- gunicorn/workers/sync.py
* Change deprecated ssl.wrap_socket() to SSLContext.wrap_context().
* Add new server hook to allow user to create custom SSLContext.
* Updated the documentation.
Fixes #1140
Signed-off-by: Tero Saarni <tero.saarni@est.tech>
> Update SSLContext handling

- docs/source/settings.rst
- gunicorn/config.py
Closes https://github.com/benoitc/gunicorn/issues/1198
I spent quite a lot of time to figure out what flag/validator value I should use for `cert-reqs` when I was trying to make the client verification optional - the request can be accepted by my server regardless the client provides a certificate or not. During the research process, I find [the SSL section of the documentation](https://docs.gunicorn.org/en/stable/settings.html#cert-reqs) could use some improvement here as new users like me would not be able to think of which number (0, 1, 2) stands for which verification mode on the spot. 
I find an open issue https://github.com/benoitc/gunicorn/issues/1198 raised in 2016 mentioning the same ambiguity about the `cert-reqs` flag in the docs that I am also facing. There wasn't a PR raised …
> docs: add examples for cert-reqs

- docs/gunicorn_ext.py
- docs/source/settings.rst
- gunicorn/config.py
- gunicorn/sock.py
- tests/test_config.py
- tests/test_ssl.py
This change defaults `SSLContext` to Python's `ssl.create_default_context()` and marks `ssl_version` option as deprecated. The option value will be ignored, and warning will be printed in stderr. The reason for deprecation is that `ssl_version` option was depending on old method of setting TLS min/max version. Rationale for ignoring the given value is that the method has not worked well anymore with modern Python versions. See discussion thread https://github.com/benoitc/gunicorn/pull/2649#discussion_r1190801170.
As an alternative, config file can be used to set the min/max values, for example:
```python
def ssl_context(conf, default_ssl_context_factory):
import ssl
context = default_ssl_context_factory()
context.minimum_version = ssl.TLSVersion.TLSv1_3
context.maximum_version = …
```
> Deprecate ssl_version option

- THANKS
- gunicorn/util.py
- gunicorn/workers/geventlet.py
- gunicorn/workers/ggevent.py
- setup.py
pkg_resources is deprecated. Use the corresponding importlib.metadata interface instead. Use the stdlib version on python >= 3.8 and use the importlib_metadata backport on older versions.
Relates: https://github.com/benoitc/gunicorn/issues/2747
Closes: https://github.com/benoitc/gunicorn/pull/2958
> replace pkg_resources.load_entry_point

- gunicorn/workers/base_async.py
- gunicorn/workers/gthread.py
- gunicorn/workers/sync.py
When a client disconnects, `resp.write(item)` would result in a `BrokenPipeError` which prevents the access from being logged.
Fixes #1060.
> Log access even when connection is closed

- gunicorn/workers/gthread.py
under Python 3.8 and sup exception is ValueError when fd has already been cleared by the system.
fix #3029
> fix gthread worker

- gunicorn/workers/workertmp.py
This PR uses `utime` to update the "Changed" timestamp of the worker's temporary file, instead of calling `fchmod(fd, 0)` & `fchmod(fd, 1)` back-and-forth (which may be problematic in some restrictive environments).
This change was made possible in Python 3.3, which added support for calling `utime` with a file descriptor.
> Use `utime` instead of `fchmod` in `WorkerTmp.notify`

- pyproject.toml
Sorry, an incorectness slept-in in #3063: the `LICENSE` file won't be properly embedded in the package. I tested this fix locally, you can merge with confidence.
Sorry again 😬
> pyproject.toml: fix embedding of the LICENSE file in the package

- SECURITY.md
Typo was introduces by myself, sorry.
Mailbox **not verified**, merely duplicated from /docs/source/community.rst
* see #3122
> Typo and email address in Security.md

- .github/workflows/lint.yml
- .github/workflows/tox.yml
- appveyor.yml
- gunicorn/__main__.py
- gunicorn/app/wsgiapp.py
- pyproject.toml
- requirements_dev.txt
- requirements_test.txt
- tox.ini
1. We want the built package to install a "gunicorn" script.
* Tell setuptools, now it reads that from `pyproject.toml`
* Fixes: https://github.com/benoitc/gunicorn/issues/3119
2. We want that script to work and reasonable output when called `gunicorn --help`
* Have CI `assert` that
3. We want the entry point to work more or less interchangeably with `python3 -m gunicorn` (that is: `__main__.py`)
* Have CI `assert` that
Driveby fixes:
4. GitHub actions finish faster when the setup-python knows which dependencies are reused
* potentially unwanted effects for private dependencies - OK, we only use PyPi hosted (and occasionally public GitHub)
* Verification: In section "Install Dependencies" logs will say "Using cached" in place of "Downloading"
5. Some python tools fail to agree with GitHub …
> restore, and from now on CI-test for entry point

- .github/workflows/tox.yml
- README.rst
- appveyor.yml
- docs/source/2023-news.rst
- docs/source/index.rst
- docs/source/install.rst
- pyproject.toml
- requirements_test.txt
- setup.cfg
- tests/workers/test_geventlet.py
- tox.ini
Resubmitted smaller changeset. Intend to fix the remainder of #3110 later.
* pytest+mac+PyPy3.9 sometimes just hangs, so this one adds an overall timeout to cancel those test runs, deferring the decision of dropping PyPy3.9 early or figuring out why.
* Linting remains broken.. which is okay, this patch does not include any bump in the CPython 3.10 used for CI linting.
Issues:
* Fixes: https://github.com/benoitc/gunicorn/issues/3045
* Closes: https://github.com/benoitc/gunicorn/issues/3046
Merge order:
* rebased #3083 and #3085 are prepended, and are not needed after merging this one
* suggest merging #3108 *before* this one
* suggest merging #2836 *after* this one
> CI: add CPython 3.12 and PyPy3.10, stop promising untested versions

- .github/workflows/tox.yml
- setup.py
- tox.ini
This PR adds Python 3.12 to the github actions. 
It seems like Gunicorn itself doesn't need any modifications but eventlet has some work to do: https://github.com/eventlet/eventlet/pull/797
> Add Python 3.12 to test matrix and add classifiers

- pyproject.toml
Eventlet 0.36.0's WebSocket implementation has a bug that prevents it from running under a Gunicorn worker (as is done by Flask-SocketIO and possibly other things): https://github.com/eventlet/eventlet/issues/946
Probably this will be fixed in the next Eventlet release but Gunicorn should exclude 0.36.0 to avoid nasty surprises downstream!
> fix(deps): exclude eventlet 0.36.0 to avoid WebSocket bug

- .github/workflows/tox.yml
- tox.ini
1. A few other PRs have degraded CI results because Github does not provide Python 3.7 on the default macos-latest runners.
* Suggestion: just drop back to macos-13, an try the macos-latest image just for a single known-good version.
* Considered alternative: keep defaults and special case the other way around: not great while the macos-14 images also have unrelated issues.
2. The tox.ini contained supersedes settings and a reference to unpleasant behaviour in a scenario we may entirely avoid by using the `package` / `no_package` flags instead of `skipsdist` and `usedevelop`.
* Suggestion: Just assert we are using tox v4 and let tox prepare something more like what we actually need for each tests
3. The upcoming Python 3.13 version comes with some interesting changes (see …
> CI: revert macos-14 runners, migrate to tox v4-exclusive settings, add Python 3.13

- gunicorn/http/errors.py
- tests/test_http.py
> Fix InvalidHTTPVersion exception str method

- gunicorn/http/body.py
- tests/requests/invalid/chunked_12.http
- tests/requests/invalid/chunked_12.py
- tests/requests/invalid/chunked_13.http
- tests/requests/invalid/chunked_13.py
Integer conversion from zero-length strings is invalid: `ValueError: invalid literal for int() with base 10: ''`
Treat it the same as invalid characters where size should be.
> gracefully handle chunked encoding missing size

- gunicorn/instrument/statsd.py
- gunicorn/workers/ggevent.py
Fixes https://github.com/benoitc/gunicorn/issues/2335. Changes are simply decoding `status` (when logging access for statsd or logging requests for gevent) from bytes to str if necessary. Tested this locally with Python 3.7 and gevent 1.4.0, and it works just fine.
> Fixed two bugs related to gevent + gunicorn + statsd.

- gunicorn/http/message.py
The shortest origin-form is a single slash, *not* empty. So refuse request lines that have two consecutive spaces where the URI should be. There should be *something* there.
Python [stdlib explicitly tells us](https://docs.python.org/3/library/urllib.parse.html#url-parsing-security ) it will not perform validation - and neither does this patch! This patch merely closes the one trivial hole that is of special interest, as it might confuse setups involving proxies and pipe-lining.
* Fixes: #3235
> refuse empty request-target in HTTP request

- .gitignore
- MANIFEST.in
- docs/Makefile
- docs/README.rst
**source** distributions should probably not contains artifacts from compiling documentation
* drive-by change: sphinx-doc.org does not have working https on the bare 2nd-level domain - link the www homepage
* drive-by change: clarify that the docs/Makefile is *generated*, recreating which could lead to BUILDDIR=_build (extra underscore) - exclude that folder too, just in case
* Fixes: #3109
> exclude generate html files from source tarballs (sdist)

- docs/source/settings.rst
- gunicorn/config.py
- gunicorn/http/message.py
- tests/requests/invalid/invalid_field_value_01.http
- tests/requests/invalid/invalid_field_value_01.py
- tests/requests/valid/invalid_field_value_01_compat.http
- tests/requests/valid/invalid_field_value_01_compat.py
**Backwards incompatible behavior** - but only in clear-cut cases of requests that are, and always have been, invalid and dangerous. Newer standards are more explicit in that they are not to be tolerated.
* first commit is just to clean up diff view, should be empty if applied after #3217
* drive-by change: attach deprecation notices to 22.0 escape hatch options
* fixes: #3144
> Refuse requests with invalid and dangerous CR/LF/NUL in header field value, as demanded by rfc9110 section 5.5

- .github/workflows/lint.yml
- docs/source/2023-news.rst
- docs/source/news.rst
- docs/source/settings.rst
- gunicorn/config.py
New CI task: complain if `docs/source/settings.rst` has changed after invoking `sphinx-build`, indicating someone (me) has forgotten to run `make -C docs html`
* Its not a tox env because I found it easier to ask git whether the file has changed.
* It will also fail if sphinx-build fails. This is good. We should know when that happens (note however, that this does not yet fail on a mistyped reference. that is, so far, just a warning.)
Proof that this works can be found in the earlier CI run of this very PR:
* https://github.com/benoitc/gunicorn/actions/runs/9185099713/job/25258482749
* it fails - which is to be expected, because only a later commit fixes includes the updated rst file.
Assumption:
* no need to duplicate between `news.rst` / `2023-news.rst` - just move the content to …
> CI: verify docs are up to date

- gunicorn/sock.py
* The error-severity message should [say what went wrong](https://knowyourmeme.com/memes/oopsie-woopsie
).
* It must not be not be omitted on the 5th error.
* The debug-severity message may add the non-news that absolutely fantastically nothing will happen in the next second.
* This one must be omitted as we are not planning to go to sleep() again.
This patch does not depend on https://github.com/benoitc/gunicorn/pull/3127 - I just noticed it in that context.
> logging: swap error/debug severity on socket creation failure

- docs/source/deploy.rst
- docs/source/faq.rst
- docs/source/news.rst
- docs/source/settings.rst
- gunicorn/config.py
- gunicorn/http/message.py
- tests/test_config.py
As pointed out in [#2650](https://github.com/benoitc/gunicorn/issues/2650#issuecomment-2064250689),  I have     introduced a regression in the now released 22.0 version. What commonly worked in the *default* installation without additional configuration broke: Passing *dynamic* path information from a front-end when the application lives in a subfolder.
- ✅ Deployments where the application does not require additional path information from the front-end proxy keep working
- ✅ Deployments where the SCRIPT_NAME is statically configured keep working
- e.g. in the application, in its environment, or in the environment of the gunicorn runtime (including in a systemd unit file)
- ❌ Deployments that depended on the ability of arbitrary requests containing a `SCRIPT_NAME` (underscore, not dash) …
> 22.0.0 regression: We need a better default treatment of SCRIPT_NAME

- docs/source/settings.rst
Added more clearly info about user name identifier (u). That will save a bit of time for developers due log configuration, like this guy https://stackoverflow.com/questions/51660511/gunicorn-access-logs-shows-empty-user
> Improve access-log-format documentation section

- gunicorn/sock.py
Implementing suggestion by reviewer https://github.com/benoitc/gunicorn/pull/3127#discussion_r1568620243 to make code more readable.
> Update sock.py by making bind list creation more readable

- gunicorn/arbiter.py
~~Commit 1 is a refactor. The others are reexec environ related.~~
~~### Commit 1~~
~~Moved `Arbiter.log.close_on_exec()` from `Arbiter.init_signals()` to `Arbiter.setup()`. Seem more appropriate.~~
~~### Commit 2~~
~~In `Arbiter.maybe_promote_master()`, cleanup more env variables passed from `Arbiter.reexec()` called in parent.~~
~~Considering whether to unset `LISTEN_PID`, `LISTEN_FDS` is handled by `systemd.listen_fds(unset_environment=True)` under `Arbiter.start()`. I leave these two env vars alone.~~
In `Arbiter.reexec()`, `GUNICORN_FD` may not be passed to the new master process,
```python
def reexec(self):
...
self.cfg.pre_exec(self)
environ = self.cfg.env_orig.copy()
environ['GUNICORN_PID'] = str(master_pid)
if self.systemd:
environ['LISTEN_PID'] = str(os.getpid()) …
```
> Typo fix for reexec related environ variables

- examples/sendfile.py
because of `@validator` decorator, the fn returns `wsgiref.validate.IteratorWrapper` instead of `gunicorn.http.wsgi.FileWrapper` which breaks sendfile
https://github.com/benoitc/gunicorn/blob/69c508ac6e4b301045d3ce21acce8b416415d4c5/gunicorn/workers/sync.py#L181-L182
> Fix sendfile.py example

- MANIFEST.in
* Fixes: #3267 (not immediately, the change merely requests inclusion in *future* source distributions)
Argument from authority: See what setuptools does & documents: https://github.com/pypa/setuptools/blob/1d2fd37368fc2381e21cd5466aeb222fc11db2db/MANIFEST.in
Confirmation:
```shell
$ python -m build
$ tar -tf dist/gunicorn-*.tar.gz | grep tox
gunicorn-23.0.0/tox.ini
```
note: if ever using setuptools-scm: .gitattributes / MANIFEST.in precedence could undo this change
> packaging: include tox.ini in sdist

- gunicorn/arbiter.py
- gunicorn/workers/ggevent.py
Hi,
As previously noted in issues #2100, #1984, #2465, #2095, #2192, and #2168 - Gunicorn isn't correctly load balancing requests across processes, even if you flip on reuse_port.
An aside to really spell out what the problem is:
As @tilgovi noted in #2101 and #2102, the root of the problem is that when the workers fork, the socket data structure from the master process is reused for each worker.  Fundamentally, this means SO_REUSEPORT doesn't work as designed, since there's really just one socket object being bound to the address.
We tried #2101 as a fix for this - but soon ran into a variety of bizarre crashes including “socket operation on non-socket” and “Bad file descriptor”.  After quite a bit of debugging, we found a use after free in Gunicorn's gevent worker …
> Fix reuse-port to balance requests across Gunicorn workers

- CONTRIBUTING.md
- docs/source/community.rst
The Community page was a little bit outdated. Specially the IRC channel info was totally wrong, causing potential help-seekers issues in finding the correct channel/network. 
Also, slightly updated the Community page text. Its not perfect, but is a noticeable improvement imho. Fixed some broken links.
> Updated IRC Channel info & Slightly improved the Community Doc
