benoitc/gunicorn

gunicorn/config.py
gunicorn/http/wsgi.py
gunicorn/util.py

assert statements will be removed if you run Python
in optimized mode (e.g. with -O flag).

Raise TypeError instead of AssertionError.

---

examples/gunicorn_rc

I'm new to gunicorn. I'm not sure if this file is still relevant, but I had to make a couple of changes to get it to work for me.

fixed syntax errors in examples/gunicorn_rc.

---

.gitignore

people should be encouraged to use a global gitignore file.
https://help.github.com/articles/ignoring-files/
related to #1007

clean gitignore

---

gunicorn/http/wsgi.py

Fix comment typos

---

docs/source/deploy.rst
examples/nginx.conf

Update example nginx configs to require Host match.

---

THANKS
gunicorn/workers/base.py

Fixes #1061.
I didn't write a test since there don't seem to be any similar tests yet,
and I'm not familiar enough with the test infrastructure.

Include request URL in error message.

---

gunicorn/glogging.py

a possible fix to #1148 . let me know

check if the auth type is Basic before getting the user name

---

gunicorn/arbiter.py

Fixed log message for listener reloading

---

docs/source/deploy.rst

I had a hard time following the instructions to get Gnicorn set up with Systemd and Nginx.  So I added some detail to the instructions on the parts I had a hard time with.

added some more detail for setting up gunicorn on systemd

---

gunicorn/arbiter.py
gunicorn/lockfile.py
gunicorn/sock.py
tests/test_arbiter.py
tests/test_lockfile.py
tests/test_sock.py

Revert "lockfile improvements"

---

gunicorn/config.py
gunicorn/glogging.py

Add the new setting `--capture-stdio` to capture output from stdio/stderr to the current log file.
fix #1271

redtirect stdio/stderr to logfile

---

docs/source/2010-news.rst
docs/source/2012-news.rst
docs/source/2013-news.rst
docs/source/2015-news.rst
docs/source/2016-news.rst
docs/source/design.rst
docs/source/faq.rst
docs/source/news.rst

Fixes the changelog bullets added for #1252, as well as a number of spelling corrections and markup improvements.

Docs: Spelling corrections & markup tweaks

---

docs/source/deploy.rst

The ExecStart didn't point to the gunicorn executable like it should.

fixed incorrect gunicorn.service file for SystemD

---

docs/source/deploy.rst

Hi.  I notices a few small issues with the Systemd documentation.  Please let me know if it needs any other fixes.
-Dave

fixed a few typos and improved clarity for systemd

---

gunicorn/util.py
gunicorn/workers/base.py

format boot tracebacks properly with reloader

---

gunicorn/app/base.py
gunicorn/util.py
tests/support.py

change __dict__ to vars function

change __dict__ to vars function

---

docs/gunicorn_ext.py
docs/source/run.rst
docs/source/settings.rst

documentation added for specify setting by environment variable. #1385

documentation added for specify setting by environment variable.

---

requirements_test.txt
tests/test_config.py

test for passing invalid cmd line arguments.

test_cmd_line_invalid_setting added.

---

tests/t.py
tests/test_config.py
tests/test_statsd.py
tests/treq.py

i check all tests and fixed them.

add empty line after some tests.

---

.travis.yml
setup.py
tox.ini

Also update package metadata.
Fixes #1439

Add new Python versions to build matrix

---

docs/source/settings.rst
gunicorn/config.py
gunicorn/workers/base.py
tests/test_config.py

Use the best available reloader when --reload is passed

---

.prospector.yaml
.travis.yml
examples/frameworks/django/testing/testing/apps/someapp/middleware.py
examples/frameworks/django/testing/testing/apps/someapp/models.py
examples/frameworks/django/testing/testing/apps/someapp/views.py
examples/frameworks/django/testing/testing/settings.py
examples/longpoll.py
examples/websocket/gevent_websocket.py
examples/websocket/websocket.py
gunicorn/util.py
gunicorn/workers/gtornado.py
requirements_test.txt
scripts/update_thanks.py
setup.cfg
tests/t.py
tests/test_config.py
tests/test_statsd.py
tests/treq.py
tox.ini

Integrate prospector into Travis CI

---

.travis.yml
requirements_test.txt

Should address https://github.com/benoitc/gunicorn/issues/1548.

pin coverage>=4.0,<4.4

---

gunicorn/util.py
tests/test_util.py
tests/test_utils.py

better handling for unix socket address in `parse_address`

Rewrite parse_address utils

---

tests/test_util.py

Improve util tests, add tests for:
- http_date
- is_ipv6
- warn

Improve util tests(add tests for http_date, is_ipv6, warn)

---

gunicorn/glogging.py

Fix access logs not emitted when using logconfig_dict

---

gunicorn/http/message.py

Remove superfluous BytesIO allocation

---

gunicorn/glogging.py
tests/test_logger.py

Fixes #1683 
Added a unit test and tests pass on my branch.
Also tested against my server and confirmed the fix works.

Fix 1683 handle malformed basic auth header

---

gunicorn/reloader.py

Handle the case where module.__file__ is None.

---

docs/source/instrumentation.rst

This tiny text made me look at code only to figure out it is possible...
Might help somebody else!

Better docs for statsd prefix

---

gunicorn/workers/gtornado.py

Fix #1728 
Tested in tornado 4.5.2 and 5.0.2, should works well in all versions.

Fix #1728 make TornadoWorker compatible with Tornado 5.X

---

docs/source/settings.rst
gunicorn/config.py

Improve `capture_output` setting documentation. [issue 1745](https://github.com/benoitc/gunicorn/issues/1745)

Improve `capture_output` setting documentation

---

docs/gunicorn_ext.py

Fix https://github.com/benoitc/gunicorn/issues/1798

Fix the settings section in documentation

---

examples/nginx.conf

PID didn't work at all on Ubuntu 16.04 with the provided sample, my commented out change does, also added logging change to conform to what is out of the box.

Pid and Logging changes

---

gunicorn/glogging.py

root and logger are same level. https://docs.python.org/2/library/logging.config.html#dictionary-schema-details

Fix root logging

---

examples/frameworks/django/testing/testing/apps/someapp/middleware.py
examples/standalone_app.py
examples/when_ready.conf.py
gunicorn/app/base.py
gunicorn/config.py
gunicorn/glogging.py
gunicorn/http/message.py
gunicorn/http/unreader.py
gunicorn/reloader.py
gunicorn/sock.py
gunicorn/workers/base.py
gunicorn/workers/base_async.py
gunicorn/workers/geventlet.py
gunicorn/workers/ggevent.py
gunicorn/workers/gthread.py
gunicorn/workers/gtornado.py
tests/test_arbiter.py
tests/test_config.py

Hello. What do you think about this?

Remove redundant super() arguments

---

gunicorn/util.py
tests/test_util.py

Maybe better implementation of `parse_address` util.

Rewrite `parse_address` util and add one test

---

gunicorn/http/wsgi.py

handle `wsgi.input_terminated` extension

---

docs/source/design.rst

When I read about the async worker the first time I had no idea about greenlets and stuff.
I think it would have helped me to get some additional context as the async worker is obviously no silver bullet.

Emphasize that full greenlet support might need additional work

---

tests/support.py
tests/test_logger.py
tests/test_statsd.py

types.SimpleNamespace is new in version 3.3.
https://docs.python.org/3/library/types.html#types.SimpleNamespace

Remove SimpleNamespace class

---

gunicorn/arbiter.py

removing duplicated try catch code :)

refactor to catch multiple execption

---

README.rst

Adding a link to your contribution guide in the README. I think this helps new users find this easily.

add info about contributions in readme

---

CONTRIBUTING.md

nitpicky, but I was reading through this and figured I'd update it

Terminology changes

---

.travis.yml
appveyor.yml
docs/site/index.html
docs/source/settings.rst
examples/echo.py
examples/log_app.py
examples/readline_app.py
examples/test.py
gunicorn/arbiter.py
gunicorn/config.py
gunicorn/glogging.py
gunicorn/http/message.py
gunicorn/http/wsgi.py
gunicorn/reloader.py
gunicorn/sock.py
gunicorn/util.py
gunicorn/workers/base.py
gunicorn/workers/geventlet.py
gunicorn/workers/gtornado.py
setup.py
tests/test_arbiter.py
tests/test_http.py
tests/test_sock.py
tox.ini

This PR backports all the commits listed in #2022 to the `19.x` branch in anticipation of one last `19.10` release.
Fixes #2022.

19.x backports

---

NOTICE
gunicorn/socketfromfd.py

fix cases where the type of socket is not correctly detected on mac.
fix #2201

Fix socketfromfd

---

docs/source/faq.rst

Update FAQ - Workers Silently Killed.

---

setup.py

Development Status of 4 - Beta seems unreasonable, so bumping that up.  This shows up in PyPi etc.

Updated Development Status 5 - Production/Stable

---

gunicorn/workers/ggevent.py

This backports #2266 from master.

Backport #2266 from master

---

gunicorn/workers/base_async.py

Fixes https://github.com/benoitc/gunicorn/issues/2303

Exit async keepalive request loop when self.alive is False

---

gunicorn/workers/base_async.py

Revert "Exit async keepalive request loop when self.alive is False"

---

docs/sitemap_gen.py
gunicorn/arbiter.py
gunicorn/glogging.py
tests/treq.py

I have not reviewed these changes yet - the original changes were contributed as patches on 19.9.0 and needed rebasing with conflicts resolved (some changes may have been discarded for simplicity in favour of changed code on `master`).
Doing that here first, then will review the changes.  Other reviewers welcome.
Fixes #1690.

Various code improvements contributed by dilyanpalauzov.

---

docs/source/settings.rst

Document --timeout 0

---

docs/source/run.rst
docs/source/settings.rst
gunicorn/app/wsgiapp.py
gunicorn/config.py
tests/config/test_cfg_with_wsgi_app.py
tests/test_config.py

Specify wsgi_app in config

---

README.rst
setup.py

Fixes https://github.com/benoitc/gunicorn/issues/2359.
Also update a couple of links to use HTTPS.

Add project_urls for PyPI

---

docs/source/install.rst

- Recommend latest (supported) Debian and Ubuntu versions
- Update provided versions of gunicorn in Debian and Ubuntu

Update Debian and Ubuntu distribution information

---

docs/source/settings.rst

just a typo fix in documentation

fix chdir documentation typo

---

setup.py

Upon pushing to PyPI, the badge on top of the readme should
automatically update

Add Python 3.10 classifier

---

gunicorn/http/body.py

integral: "In mathematics, an integral assigns numbers to functions in a way that describes displacement, area, volume, and other concepts that arise by combining infinitesimal data."
integer: an int type

integral? that took me a while to figure out

---

gunicorn/http/wsgi.py

ValueError: count must be a positive integer (got 0)

Solving issue #2692

---

gunicorn/arbiter.py
gunicorn/config.py
gunicorn/debug.py
gunicorn/glogging.py
gunicorn/http/message.py
gunicorn/sock.py
gunicorn/systemd.py
gunicorn/util.py
gunicorn/workers/geventlet.py
gunicorn/workers/ggevent.py
gunicorn/workers/gtornado.py

Follow up PR to #2927 discussion which only focuses on fixing pycodestyle issues to make sure CI lint passes
Here's the [🔗 to workflow which has both #2927 and this PR merged](https://github.com/samypr100/gunicorn/actions?query=branch%3Aci-improvements-with-pycodestyle-fixes) to show linting workflow fully working

Fixing errors reported by pycodestyle

---

gunicorn/workers/base.py

#2491 
Debug level might not be practical to enable in production.

Use warning level for 'Bad request' logs

---

docs/source/deploy.rst

Added the `proxy_ignore_client_abort on;` in doc.
Would it be possible to review and approve this change?

Fixes #1695

---

gunicorn/http/message.py
tests/requests/invalid/022.http
tests/requests/invalid/022.py
tests/requests/invalid/023.http
tests/requests/invalid/023.py
tests/requests/invalid/024.http
tests/requests/invalid/024.py

Updating Content-Length Handling

---

gunicorn/workers/gthread.py

revert change considering connection as idle

---

docs/source/design.rst

Python2 is not supported anymore.

Remove Python2 note

---

README.rst
docs/source/index.rst
docs/source/install.rst
setup.py

Document Python 3.7 requirement

---

examples/example_config.py

tiny update in examples folder

update example_config with latest settings

---

gunicorn/http/body.py

more in bug report: https://github.com/benoitc/gunicorn/issues/2684
Fixes #2684

Fix problem that may happen after interrupted chunk-encoding request

---

docs/source/settings.rst
gunicorn/config.py

getgrnam is under grp module instead of pwd

Fix typo in the settings.rst
